/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-06-05 02:01:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.goods;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class GoodsView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      java.util.Hashtable outputTable = null;
      outputTable = (java.util.Hashtable) _jspx_page_context.getAttribute("outputTable", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (outputTable == null){
        outputTable = new java.util.Hashtable();
        _jspx_page_context.setAttribute("outputTable", outputTable, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");

	ArrayList goodsList = (ArrayList)outputTable.get("goodsList");
	Hashtable goodsTable = (Hashtable)goodsList.get(0);

	String id = (String)session.getAttribute("id");
	String code = (String)goodsTable.get("CODE");
	String name = (String)goodsTable.get("NAME");
	String company = (String)goodsTable.get("COMPANY");
	String country = (String)goodsTable.get("COUNTRY");
	String quantity = (String)goodsTable.get("QUANTITY");
	String amount = (String)goodsTable.get("GOODS_AMOUNT");
	String amountKo = amount;
	String goodsComment = (String)goodsTable.get("GOODS_COMMENT");
	String parPrice = (String)goodsTable.get("PAR_PRICE");
	String sc_name = (String)goodsTable.get("SC_NAME");
	String sc_code = (String)goodsTable.get("SC_CODE");
	String mc_name = (String)goodsTable.get("MC_NAME");
	String mc_code = (String)goodsTable.get("MC_CODE");

	System.out.println("상세정보 SUB : "+sc_name+" MIDDLE : "+mc_name);
	
	if (amount.equals("0"))
	{
		amountKo = "품절";
	}
	else
	{
		amountKo = "재고있음";
	}

	String loginYn = "N";
	if(session.getAttribute("loginYn")!=null && ((String)session.getAttribute("loginYn")).equals("Y"))
	{
		loginYn = "Y";
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- <script src=\"../js/jquery-1.6.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/jquery.jqzoom-core.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/jquery.jqzoom.css\" type=\"text/css\"> -->\r\n");
      out.write("\r\n");
      out.write("<SCRIPT>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t//상품 즉시구매페이지 가기\r\n");
      out.write("\tfunction goodsBuyAction()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar f = document.goodsPageForm;\r\n");
      out.write("\t\tvar amount = f.count.value;\r\n");
      out.write("\r\n");
      out.write("\t\tdocument.location.href=\"/goodsServlet.mo?func=goods_010&amount=\"+amount+\"&code=");
      out.print(code);
      out.write("\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction goList()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t//리스트, 서브리스트, 장바구니, 관심상품에 from 달아놓았음. 이거 나중에 꺼내쓰면됨\r\n");
      out.write("\t\t//이동시 전에 보던 페이지로 이동할때 사용\r\n");
      out.write("\t\tdocument.location.href=\"/goodsServlet.mo?func=goods_001&middleCategory=");
      out.print(mc_code);
      out.write("\";\r\n");
      out.write("\t}\r\n");
      out.write("\t//장바구니에 상품등록\r\n");
      out.write("\tfunction goodsCartAction()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif ('");
      out.print(loginYn);
      out.write("' == 'N')\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif (confirm(\"로그인이 필요한 메뉴입니다. \\n로그인하시겠습니까?\"))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tdocument.location.href=\"/memberServlet.mo?func=member_004\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar f = document.goodsPageForm;\r\n");
      out.write("\t\tf.func.value= \"goods_004\";\r\n");
      out.write("\t\tf.amount.value=f.count.value;\r\n");
      out.write("\t\tf.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction goodsInterestAction(code)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif ('");
      out.print(loginYn);
      out.write("' == 'N')\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif (confirm(\"로그인이 필요한 메뉴입니다. \\n로그인하시겠습니까?\"))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tdocument.location.href=\"/memberServlet.mo?func=member_004\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(confirm(\"관심상품에 추가하시겠습니까?\"))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tdocument.location.href=\"/goodsServlet.mo?func=goods_CDH001&code=\"+code;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t//관리자 상품수정\r\n");
      out.write("\tfunction goodsStatus()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.location.href='managerOrderServlet.mo?func=managerOrder_024';\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction resumePrice()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar f = document.goodsPageForm;\r\n");
      out.write("\t\tvar amount = f.count.value;\r\n");
      out.write("\t\tvar price = $('#price').text();\r\n");
      out.write("\t\tvar inventory = $('#inventory').text();\r\n");
      out.write("\r\n");
      out.write("\t\tprice = deleteComma(price);\r\n");
      out.write("/*\r\n");
      out.write("\t\t재고보다 주문수량이 많으면 얼럿띄움\r\n");
      out.write("\t\tif (amount > inventory)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"재고가 부족합니다. 재고를 확인해주세요.\");\r\n");
      out.write("\t\t\tf.count.value = inventory;\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("*/\r\n");
      out.write("\t\tvar totalCash = price * amount;\r\n");
      out.write("\t\t$('#totalPrice').text(insertComma(totalCash));\r\n");
      out.write("\t\t$('#price').text(insertComma(price));\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#price').text(insertComma(\"");
      out.print(parPrice);
      out.write("\"));\r\n");
      out.write("\t\t$('#totalPrice').text(insertComma(\"");
      out.print(parPrice);
      out.write("\"));\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('.detail_img_s').find('img').each(function(){\r\n");
      out.write("\t\t\t$(this).hide();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('.detail_img_s').find('img').eq(0).show();\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction next_pic()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar container = $('.detail_img_s');\r\n");
      out.write("\t\tvar img = container.find('img');\r\n");
      out.write("\r\n");
      out.write("\t\tvar first = img.eq(0);\r\n");
      out.write("\t\tvar second = img.eq(1);\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\tif (second.attr('src') != undefined)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t//\t$(\"#img_num\").html(''+img.attr('img_num'));\r\n");
      out.write("\t\t\tfirst.fadeOut().appendTo(container);\r\n");
      out.write("\t\t\tsecond.fadeIn();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction prev_pic()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar container = $('.detail_img_s');\r\n");
      out.write("\t\tvar img = container.find('img');\r\n");
      out.write("\r\n");
      out.write("\t\tvar last = $('.detail_img_s img:last');\r\n");
      out.write("\t\tvar first = img.eq(0);\r\n");
      out.write("\r\n");
      out.write("\t\tif (first.attr('src') != last.attr('src'))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t//\t$(\"#img_num\").html(''+img.attr('img_num'));\r\n");
      out.write("\t\t\tfirst.fadeOut()\r\n");
      out.write("\t\t\tlast.prependTo(container).fadeIn();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction submenuAction2(subcode, subname)\r\n");
      out.write("\t{\r\n");
      out.write("\t\t//alert(middleCategory);\r\n");
      out.write("\t\t//document.location.href=\"/goodsServlet.mo?func=goods_001?middleCategory=\"+middleCategory+\"\";\r\n");
      out.write("\t\tdocument.location.href=\"/goodsServlet.mo?func=goods_007&middleCategory=");
      out.print(mc_code);
      out.write("&subcode=\"+subcode+\"&subname=\"+subname+\"\";\r\n");
      out.write("\t}\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("<div><!-- 리스트 화면 상단 바 -->\r\n");
      out.write("\t<img src=\"/images/goodsList/t_details.png\">\r\n");
      out.write("</div>\r\n");
      out.write("<span style=\"margin-left:30px;\">현제 페이지 : <A href=\"/goodsServlet.mo?func=goods_001\">홈</A>><A href=\"JavaScript:menuAction('");
      out.print(mc_code);
      out.write("');\">");
      out.print(mc_name);
      out.write("</A>><A href=\"JavaScript:submenuAction2('");
      out.print(sc_code);
      out.write("', '");
      out.print(sc_name);
      out.write("');\">");
      out.print(sc_name);
      out.write("</A></span>\t\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"top_radius\">&nbsp;&nbsp;<img src=\"/images/common/bul_02_01.gif\" align=\"absmiddle\">&nbsp;&nbsp;<B>");
      out.print(mc_name);
      out.write('/');
      out.print(sc_name);
      out.write("</B></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<FORM name=\"goodsPageForm\" method=\"GET\" action=\"/goodsServlet.mo\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"func\" value=\"goods_003\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"code\" value=");
      out.print(code);
      out.write(">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"name\" value=");
      out.print(name);
      out.write(">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"company\" value=");
      out.print(company);
      out.write(">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"country\" value=");
      out.print(country);
      out.write(">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"quantity\" value=");
      out.print(quantity);
      out.write(">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"amount\" value=");
      out.print(amount);
      out.write(">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"goodsComment\" value=");
      out.print(goodsComment);
      out.write(">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"parPrice\" value=");
      out.print(parPrice);
      out.write(">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<DIV id=\"goods_detail_wrap\">\r\n");
      out.write("\t<div class=\"detail_img_s\">\r\n");
      out.write("\t");

		ArrayList goodsImgList = (ArrayList)goodsTable.get("FILE_LIST");
		
		for(int i = 0; i<goodsImgList.size() ; i++)
		{	//System.out.println(goodsImgList.get(i));
			Hashtable goodsImgTable = (Hashtable)goodsImgList.get(i);
			String path = (String)goodsImgTable.get("PATH");
			String saveName = (String)goodsImgTable.get("SAVE_NAME");
			saveName = "/"+saveName;
			path = "/"+path.substring(path.indexOf("upfile"));
			
			System.out.println("이미지경로 : "+path+saveName);
			
	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<A href=\"/goodsServlet.mo?func=goods_kww001&imgSrc=");
      out.print(path);
      out.write("&imgName=");
      out.print(saveName);
      out.write("&name=");
      out.print(name);
      out.write("\" target=\"_blank\"><img src=\"");
      out.print(path+saveName);
      out.write("\" img_num=\"");
      out.print(i+1);
      out.write("\" border=\"0\"></A>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"margin-top:390px; margin-left:40px; position:absolute;\"><font color=\"#c9c9c9\"><h5>이미지를 클릭하시면 원본이미지를 보실수 있습니다!!</h4></font></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"right_arrow\" onclick=\"next_pic();\">\r\n");
      out.write("\t\t<img src=\"/images/common/right_arrow.jpg\" style=\"cursor:hand;\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<span id=\"img_num\">\r\n");
      out.write("\t\r\n");
      out.write("\t</span>\r\n");
      out.write("\t<div class=\"left_arrow\" onclick=\"prev_pic();\">\r\n");
      out.write("\t\t<img src=\"/images/common/left_arrow.jpg\" style=\"cursor:hand;\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<DIV id=\"goods_detail\">\r\n");
      out.write("\r\n");
      out.write("\t\t<TABLE cellspacing=\"0\" cellpadding=\"0\" height=\"410\">\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD width=\"100px\" bgcolor=\"#eeeeee\" height= \"40px\" style=\"border-bottom: 1px solid #c0c0c0;border-top: 1px solid #c0c0c0;\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/images/common/5.gif\" style=\"margin-left:10px\">&nbsp;&nbsp;상품명</TD>\r\n");
      out.write("\t\t\t\t<TD width=\"400px\"  style=\"border-bottom: 1px solid #c0c0c0;border-top: 1px solid #c0c0c0;\">&nbsp;&nbsp;&nbsp;");
      out.print(name);
      out.write("</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD width=\"100px\" bgcolor=\"#eeeeee\" height= \"40px\" style=\"border-bottom: 1px solid #c0c0c0;\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/images/common/5.gif\" style=\"margin-left:10px\">&nbsp;&nbsp;제조사</TD>\r\n");
      out.write("\t\t\t\t<TD width=\"400px\"  style=\"border-bottom: 1px solid #c0c0c0;\">&nbsp;&nbsp;&nbsp;");
      out.print(company);
      out.write("</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD width=\"100px\" bgcolor=\"#eeeeee\" height= \"40px\" style=\"border-bottom: 1px solid #c0c0c0;\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/images/common/5.gif\" style=\"margin-left:10px\">&nbsp;&nbsp;원산지</TD>\r\n");
      out.write("\t\t\t\t<TD width=\"400px\"  style=\"border-bottom: 1px solid #c0c0c0;\">&nbsp;&nbsp;&nbsp;");
      out.print(country);
      out.write("</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD width=\"100px\" bgcolor=\"#eeeeee\" height= \"40px\" style=\"border-bottom: 1px solid #c0c0c0;\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/images/common/5.gif\" style=\"margin-left:10px\">&nbsp;&nbsp;내용량</TD>\r\n");
      out.write("\t\t\t\t<TD width=\"400px\"  style=\"border-bottom: 1px solid #c0c0c0;\">&nbsp;&nbsp;&nbsp;");
      out.print(quantity);
      out.write("</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD width=\"100px\" bgcolor=\"#eeeeee\" height= \"40px\" style=\"border-bottom: 1px solid #c0c0c0;\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/images/common/5.gif\" style=\"margin-left:10px\">&nbsp;&nbsp;상품정보</TD>\r\n");
      out.write("\t\t\t\t<TD width=\"400px\"  style=\"border-bottom: 1px solid #c0c0c0;\">");
      out.print(goodsComment);
      out.write("</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD width=\"100px\" bgcolor=\"#eeeeee\" height= \"40px\" style=\"border-bottom: 1px solid #c0c0c0;\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/images/common/5.gif\" style=\"margin-left:10px\">&nbsp;&nbsp;재고</TD>\r\n");
      out.write("\t\t\t\t<TD width=\"400px\"  style=\"border-bottom: 1px solid #c0c0c0;\"><SPAN id=\"inventory\">&nbsp;&nbsp;&nbsp;");
      out.print(amountKo);
      out.write("</SPAN></TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD width=\"100px\" bgcolor=\"#eeeeee\" height= \"40px\" style=\"border-bottom: 1px solid #c0c0c0;\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/images/common/5.gif\" style=\"margin-left:10px\">&nbsp;&nbsp;구매수량</TD>\r\n");
      out.write("\t\t\t\t<TD width=\"400px\"  style=\"border-bottom: 1px solid #c0c0c0;\">&nbsp;&nbsp;&nbsp;<input type=\"text\" name=\"count\" id=\"count\" value=\"1\" size=\"1\" onkeyup=\"resumePrice();\"></TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD width=\"100px\" bgcolor=\"#eeeeee\" height= \"40px\" style=\"border-bottom: 1px solid #c0c0c0;\" >\r\n");
      out.write("\t\t\t\t\t<img src=\"/images/common/5.gif\" style=\"margin-left:10px\">&nbsp;&nbsp;가격</TD>\r\n");
      out.write("\t\t\t\t<TD width=\"400px\"  style=\"border-bottom: 1px solid #c0c0c0;\">&nbsp;&nbsp;&nbsp;<SPAN id=\"price\"></SPAN><SPAN>원</SPAN></TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD width=\"100px\" bgcolor=\"#eeeeee\" height= \"40px\" style=\"border-bottom: 1px solid #c0c0c0;\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/images/common/5.gif\" style=\"margin-left:10px\">&nbsp;&nbsp;총 결재금액</TD>\r\n");
      out.write("\t\t\t\t<TD width=\"400px\"  style=\"border-bottom: 1px solid #c0c0c0;\">&nbsp;&nbsp;&nbsp;<FONT color=\"red\" size=\"3\"><B><SPAN id=\"totalPrice\"></SPAN></B></FONT><SPAN>원</SPAN></TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t</TABLE>\r\n");
      out.write("\t</DIV>\r\n");
      out.write("\t<DIV id=\"goodsViewButton\">\r\n");
      out.write("\t\t<img src=\"/images/goodsView/bt_cart.png\" onclick=\"goodsCartAction();\">\r\n");
      out.write("\t\t<img src=\"/images/goodsView/bt_buy.gif\" onclick=\"goodsBuyAction();\">\r\n");
      out.write("\t\t<img src=\"/images/goodsView/bt_wish.png\" onclick=\"goodsInterestAction('");
      out.print(code);
      out.write("');\">\r\n");
      out.write("\t\t<img src=\"/images/goodsView/cart_bt_goshopping.gif\" height=\"40\" onclick=\"goList();\">\r\n");

if(session.getAttribute("adminYn")!=null && ((String)session.getAttribute("adminYn")).equals("Y"))
		{

      out.write("\r\n");
      out.write("\t\t<input type=\"button\" value=\"상품관리페이지가기\" onclick=\"goodsStatus()\">\r\n");

		}

      out.write("\r\n");
      out.write("\t</DIV>\r\n");
      out.write("</DIV>\r\n");
      out.write("</FORM>\r\n");
      out.write("<div align=\"center\" style=\"margin-top:600px; margin-left:50px; border: 5px #eeeeee solid; padding=10px;\">\r\n");
      out.write("\t<img src=\"/images/goodsView/bgbinfo.jpg\">\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
