/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-06-05 05:41:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.goods;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class GoodsBuy_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      java.util.Hashtable outputTable = null;
      outputTable = (java.util.Hashtable) _jspx_page_context.getAttribute("outputTable", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (outputTable == null){
        outputTable = new java.util.Hashtable();
        _jspx_page_context.setAttribute("outputTable", outputTable, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");

	ArrayList shoppingCartList = (ArrayList)outputTable.get("shoppingCartList");
	ArrayList userInfoList = (ArrayList)outputTable.get("userInfoList");
	ArrayList bankList = (ArrayList)outputTable.get("bankList");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<SCRIPT>\r\n");
      out.write("\t//결재금액 계산\r\n");
      out.write("\tfunction resumePrice()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar f = document.goodsPageForm;\r\n");
      out.write("\t\tvar amount = f.count.value;\r\n");
      out.write("\t\tvar price = $('#price').text();\r\n");
      out.write("\t\tvar inventory = $('#inventory').text();\r\n");
      out.write("\r\n");
      out.write("\t\tprice = deleteComma(price);\r\n");
      out.write("/*\r\n");
      out.write("\t\t재고보다 주문수량이 많으면 얼럿띄움\r\n");
      out.write("\t\tif (amount > inventory)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"재고가 부족합니다. 재고를 확인해주세요.\");\r\n");
      out.write("\t\t\tf.count.value = inventory;\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("*/\r\n");
      out.write("\t\tvar totalCash = price * amount;\r\n");
      out.write("\t\t$('#totalPrice').text(insertComma(totalCash));\r\n");
      out.write("\t\t$('#price').text(insertComma(price));\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction deleteAction(code)\r\n");
      out.write("\t{\r\n");
      out.write("\t//\tvar f = document.shoppingCart;\r\n");
      out.write("\t//\tf.code.value = code;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.location.href=\"/goodsServlet.mo?func=goods_006&code=\"+code;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//체크박스 전체선택\r\n");
      out.write("\tfunction allCheck()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar f = document.shoppingCart;\r\n");
      out.write("\t\tvar check = true;\r\n");
      out.write("\t\tif (f.selectAll.checked ==true)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tcheck = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tcheck = false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar chklen = f.checkItem.length;\r\n");
      out.write("\r\n");
      out.write("\t\t// 체크박스 갯수만큼 for 문을 돌려 체크된 넘의 value값을 가져온다.\r\n");
      out.write("\t\tfor(i=0; i<chklen; i++)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tf.checkItem[i].checked = check;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//주소지의 값이 변경되면 기본주소지와 새주소지 테이블이 뿌려지는 스크립트\r\n");
      out.write("\tfunction addrChange()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar f = document.addrSelect;\r\n");
      out.write("\r\n");
      out.write("\t\tif(document.getElementsByName(\"shoppingAddress\")[0].checked)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tnewAddrTable.style.display = \"none\";\r\n");
      out.write("\t\t\tdefaultAddrTable.style.display = \"\";\r\n");
      out.write("\t\t\tdocument.shoppingCart.whereInven.value=\"Y\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tdefaultAddrTable.style.display = \"none\";\r\n");
      out.write("\t\t\tnewAddrTable.style.display = \"\";\r\n");
      out.write("\t\t\tdocument.shoppingCart.whereInven.value=\"N\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//선불과 착불여부를 체크한다.\r\n");
      out.write("\tfunction inventoryChange()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar f = document.addrSelect;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(document.getElementsByName(\"inventorySelect\")[0].checked)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tinventory.style.display = \"\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tinventory.style.display = \"none\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t//결제방법 체크\r\n");
      out.write("\tfunction payWayChoice()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar f = document.payWayForm;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(f.payway[0].checked)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tpayCashInfo.style.display = \"none\";\r\n");
      out.write("\t\t\tpayCard.style.display = \"\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tpayCard.style.display = \"none\";\r\n");
      out.write("\t\t\tpayCashInfo.style.display = \"\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t//구매좀하자\r\n");
      out.write("\tfunction buyAction()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t//체크박스의 갯수를 변수에 담는다.\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar f = document.shoppingCart;\r\n");
      out.write("\r\n");
      out.write("\t\tvar pwf = document.payWayForm;\r\n");
      out.write("\r\n");
      out.write("\t\tvar daf = document.defaultAddrForm;\r\n");
      out.write("\t\tvar naf = document.newAddrForm;\r\n");
      out.write("\r\n");
      out.write("\t\tvar pbcf = document.payByCardForm;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\tvar chklen = document.getElementsByName(\"checkItem\").length;\r\n");
      out.write("\r\n");
      out.write("\t\tif (f.comment.value == null)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tf.comment.value = \"\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (f.cardCheckYn.value == \"Y\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar flag = true;\r\n");
      out.write("\t\t\t//체크박스 갯수만큼 for 문을 돌려 체크된 넘의 value값을 가져온다.\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfor(var i = 0; i<chklen; i++)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tvar amount = document.getElementsByName(\"amount\")[i].value;\r\n");
      out.write("\t\t\t\tvar code = \"\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tcode = document.getElementsByName(\"code\")[i].value;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tdocument.getElementsByName(\"checkItem\")[i].value = amount + code;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif(document.getElementsByName(\"checkItem\")[i].checked == true)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tflag = true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (flag)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tfor (var i = 0; i < 2; i++)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tif (document.getElementsByName(\"payway\")[i].checked == true)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tf.whereCash.value = document.getElementsByName(\"payway\")[i].value;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tfor (var i = 0; i < 2; i++)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tif (document.getElementsByName(\"shoppingAddress\")[i].checked == true)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tvar whereAddr = document.getElementsByName(\"shoppingAddress\")[i].value;\r\n");
      out.write("\t\t\t\t\t\tf.whereAddr.value = whereAddr;\r\n");
      out.write("\t\t\t\t\t\tif (whereAddr == 'defaultAddr')\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\tf.name.value = daf.name.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.zipCode1.value = daf.zipCode1.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.zipCode2.value = daf.zipCode2.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.addr1.value = daf.addr1.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.addr2.value = daf.addr2.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.home1.value = daf.home1.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.home2.value = daf.home2.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.home3.value = daf.home3.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.mobile1.value = daf.mobile1.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.mobile2.value = daf.mobile2.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.mobile3.value = daf.mobile3.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.office1.value = daf.office1.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.office2.value = daf.office2.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.office3.value = daf.office3.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.comment.value = daf.comment.value;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\telse if (whereAddr == 'newAddr')\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\tf.zipCode1.value = naf.zipCode1.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.zipCode2.value = naf.zipCode2.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.addr1.value = naf.addr1.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.addr2.value = naf.addr2.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.home1.value = naf.home1.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.home2.value = naf.home2.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.home3.value = naf.home3.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.mobile1.value = naf.mobile1.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.mobile2.value = naf.mobile2.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.mobile3.value = naf.mobile3.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.office1.value = naf.office1.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.office2.value = naf.office2.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.office3.value = naf.office3.value;\r\n");
      out.write("\t\t\t\t\t\t\tf.comment.value = naf.comment.value;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse if (document.getElementsByName(\"inventorySelect\")[i].checked == true)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tf.whereInven.value = document.getElementsByName(\"inventorySelect\")[i].value;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tfor (var i = 0; i < 2; i++)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tif (document.getElementsByName(\"inventorySelect\")[i].checked == true)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tf.whereInven.value = document.getElementsByName(\"inventorySelect\")[i].value;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (f.cn1.value != pbcf.cn1.value)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\talert(\"카드 입력정보가 변경되었습니다. 다시 확인해 주시기 바랍니다.\");\r\n");
      out.write("\t\t\t\t\tcardCheckYn = \"N\";\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse if (f.cn2.value != pbcf.cn2.value)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\talert(\"카드 입력정보가 변경되었습니다. 다시 확인해 주시기 바랍니다.\");\r\n");
      out.write("\t\t\t\t\tcardCheckYn = \"N\";\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse if (f.cn3.value != pbcf.cn3.value)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\talert(\"카드 입력정보가 변경되었습니다. 다시 확인해 주시기 바랍니다.\");\r\n");
      out.write("\t\t\t\t\tcardCheckYn = \"N\";\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse if (f.cn4.value != pbcf.cn4.value)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\talert(\"카드 입력정보가 변경되었습니다. 다시 확인해 주시기 바랍니다.\");\r\n");
      out.write("\t\t\t\t\tcardCheckYn = \"N\";\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse if (f.card_end_month.value != pbcf.card_end_month.value)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\talert(\"카드 입력정보가 변경되었습니다. 다시 확인해 주시기 바랍니다.\");\r\n");
      out.write("\t\t\t\t\tcardCheckYn = \"N\";\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse if (f.card_end_year.value != pbcf.card_end_year.value)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\talert(\"카드 입력정보가 변경되었습니다. 다시 확인해 주시기 바랍니다.\");\r\n");
      out.write("\t\t\t\t\tcardCheckYn = \"N\";\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse if (f.card_pw.value != pbcf.card_pw.value)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\talert(\"카드 입력정보가 변경되었습니다. 다시 확인해 주시기 바랍니다.\");\r\n");
      out.write("\t\t\t\t\tcardCheckYn = \"N\";\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse if (f.card_jumin1.value != pbcf.card_jumin1.value)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\talert(\"카드 입력정보가 변경되었습니다. 다시 확인해 주시기 바랍니다.\");\r\n");
      out.write("\t\t\t\t\tcardCheckYn = \"N\";\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse if (f.card_jumin2.value != pbcf.card_jumin2.value)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\talert(\"카드 입력정보가 변경되었습니다. 다시 확인해 주시기 바랍니다.\");\r\n");
      out.write("\t\t\t\t\tcardCheckYn = \"N\";\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tf.func.value = \"goods_008\";\r\n");
      out.write("\t\t\t\tf.submit();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"구매하실 상품을 선택해 주세요.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"카드정보를 입력해 주세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 카드 검사\r\n");
      out.write("\tfunction cardCheckAction()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar f = document.payByCardForm;\r\n");
      out.write("\r\n");
      out.write("\t\tif(f.cn1.value==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\" 카드 번호를 입력하세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(!isNum(f.cn1.value))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"카드번호는 숫자만 입력 가능합니다.\");\r\n");
      out.write("\t\t\tf.cn1.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(f.cn1.value.length!=4)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\" 카드번호의 길이를 확인하세요.\");\r\n");
      out.write("\t\t\tf.cn1.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(f.cn2.value==\"\")\r\n");
      out.write("\t\t{\tf.cn1.select();\r\n");
      out.write("\t\t\twindow.alert(\" 카드 번호를 입력하세요.\");\r\n");
      out.write("\t\t\tf.cn2.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(!isNum(f.cn2.value))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"카드번호는 숫자만 입력 가능합니다.\");\r\n");
      out.write("\t\t\tf.cn2.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(f.cn2.value.length!=4)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\" 카드번호의 길이를 확인하세요.\");\r\n");
      out.write("\t\t\tf.cn2.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(!isNum(f.cn3.value))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"카드번호는 숫자만 입력 가능합니다.\");\r\n");
      out.write("\t\t\tf.cn3.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(f.cn3.value==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\" 카드 번호를 입력하세요.\");\r\n");
      out.write("\t\t\tf.cn3.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(f.cn3.value.length!=4)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"세번째 카드번호의 길이를 확인하세요.\");\r\n");
      out.write("\t\t\tf.cn3.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\tif(!isNum(f.cn4.value))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"카드번호는 숫자만 입력 가능합니다.\");\r\n");
      out.write("\t\t\tf.cn4.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\telse if(f.cn4.value==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\" 카드 번호를 입력하세요.\");\r\n");
      out.write("\t\t\tf.cn4.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(f.cn4.value.length!=4)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"네번째 카드번호의 길이를 확인하세요.\");\r\n");
      out.write("\t\t\tf.cn4.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//비밀번호 체크\r\n");
      out.write("\t\tif(f.card_pw.value==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("\t\t\tf.card_pw.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(!isNum(f.card_pw.value))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"비밀번호는 숫자만 입력 가능합니다.\");\r\n");
      out.write("\t\t\tf.card_pw.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// 주민번호 체크\r\n");
      out.write("\t\tif(f.card_jumin1.value==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"주민등록번호 앞자리를 입력하세요.\");\r\n");
      out.write("\t\t\tf.card_jumin1.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(f.card_jumin2.value==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"주민등록번호 뒷자리를 입력하세요.\");\r\n");
      out.write("\t\t\tf.card_jumin2.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(f.card_jumin1.value.length!=6)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"주민등록번호 앞자리의 길이를 확인하세요.\");\r\n");
      out.write("\t\t\tf.card_jumin1.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(f.card_jumin2.value.length!=7)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"주민등록번호 뒷자리의 길이를 확인하세요.\");\r\n");
      out.write("\t\t\tf.card_jumin2.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(!isNum(f.card_jumin1.value))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"주민등록번호는 숫자만 입력 가능합니다.\");\r\n");
      out.write("\t\t\tf.card_jumin1.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(!isNum(f.card_jumin2.value))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"주민등록번호는 숫자만 입력 가능합니다.\");\r\n");
      out.write("\t\t\tf.card_jumin2.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfor (var i = 0;i<2 ;i++ )\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar f = document.shoppingCart;\r\n");
      out.write("\t\t\tvar pbcf = document.payByCardForm;\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (document.getElementsByName(\"payway\")[i].checked == true)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tf.whereCash.value = document.getElementsByName(\"payway\")[i].value;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (f.whereCash.value == \"card\")\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tf.cn1.value= pbcf.cn1.value;\r\n");
      out.write("\t\t\t\t\tf.cn2.value= pbcf.cn2.value;\r\n");
      out.write("\t\t\t\t\tf.cn3.value= pbcf.cn3.value;\r\n");
      out.write("\t\t\t\t\tf.cn4.value= pbcf.cn4.value;\r\n");
      out.write("\t\t\t\t\tf.card_end_month.value= pbcf.card_end_month.value;\r\n");
      out.write("\t\t\t\t\tf.card_end_year.value= pbcf.card_end_year.value;\r\n");
      out.write("\t\t\t\t\tf.card_pw.value= pbcf.card_pw.value;\r\n");
      out.write("\t\t\t\t\tf.card_jumin1.value= pbcf.card_jumin1.value;\r\n");
      out.write("\t\t\t\t\tf.card_jumin2.value= pbcf.card_jumin2.value;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tajaxCardCheck();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction ajaxCardCheck()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype: \"POST\", \r\n");
      out.write("\t\t\turl: \"/goodsServlet.mo\",\r\n");
      out.write("\t\t\tdataType: \"text\",\r\n");
      out.write("\t\t\tdata: \"func=goods_009&cn1=\" + $('#cn1').val() +\"&cn2=\" + $('#cn2').val() +\"&cn3=\" + $('#cn3').val() +\"&cn4=\" + $('#cn4').val() +\"&card_end_month=\" + $('#card_end_month').val() +\"&card_end_year=\" + $('#card_end_year').val() +\"&card_pw=\" + $('#card_pw').val() +\"&card_jumin1=\" + $('#card_jumin1').val() +\"&card_jumin2=\" + $('#card_jumin2').val(), \r\n");
      out.write("\t\t\tsuccess: function(text){\r\n");
      out.write("\t\t\t\tvar resultText = trim(text);\r\n");
      out.write("\t\t\t\tvar resultArr = resultText.split(\"^\");\r\n");
      out.write("\t\t\t\tvar resultCode = resultArr[0];\r\n");
      out.write("\t\t\t\tvar resultCard = resultArr[1];\r\n");
      out.write("\t\t\t\tvar resultMessage = \"<FONT color='red'>\"+resultCard +\"</FONT>\";\r\n");
      out.write("\t\t\t\tif(resultCode==\"1\")\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t$('#cardCheckYn').attr('value', 'Y');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t$('#cardCheckYn').attr('value', 'N');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$('#cardCheckMessage').html(resultMessage);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 우편번호 검색\r\n");
      out.write("\tfunction searchZipCodeAction()\r\n");
      out.write("\t{\r\n");
      out.write("\t\twindow.open(\"/commonServlet.mo?func=common_001\", \"zipSearchOpen\", \"toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=no, width=420, height=500\");\r\n");
      out.write("\t}\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("<div><!-- 관심상품 화면 상단 바 -->\r\n");
      out.write("\t<img src=\"/images/order/t_order.png\">\r\n");
      out.write("</div>\r\n");
      out.write("<span style=\"margin-left:30px;\">현제 페이지 : <A href=\"/goodsServlet.mo?func=goods_001\">홈</A>>구매페이지\r\n");
      out.write("<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t<tr><td colspan=\"2\" height=\"20\"></td></tr>\r\n");
      out.write("\t<tr> \r\n");
      out.write("\t\t<td width=\"10\"><img src=\"/images/common/bul_02_01.gif\"></td>\r\n");
      out.write("\t\t<td class=\"font16_title\"><font color=\"333333\"><B>구매페이지</B></font></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<hr color=\"#eeeeee\" noshade>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"buyWrap\">\r\n");
      out.write("<TABLE>\r\n");
      out.write("\t<FORM name=\"shoppingCart\" method=\"POST\" action=\"goodsServlet.mo\">\r\n");
      out.write("\t\t<INPUT type=\"hidden\" name=\"func\" value=\"goods_007\">\r\n");
      out.write("\t\t<INPUT type=\"hidden\" name=\"whereInven\" value=\"\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 추가한 인풋 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"whereAddr\" value=\"\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"whereCash\" value=\"\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"name\" value=\"\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"zipCode1\" value=\"\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"zipCode2\" value=\"\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"addr1\" value=\"\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"addr2\" value=\"\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"home1\" value=\"\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"home2\" value=\"\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"home3\" value=\"\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"mobile1\" value=\"\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"mobile2\" value=\"\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"mobile3\" value=\"\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"office1\" value=\"\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"office2\" value=\"\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"office3\" value=\"\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"comment\" value=\"\">\r\n");
      out.write("\t<!--결제방법-->\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"cn1\" value=\"\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"cn2\" value=\"\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"cn3\" value=\"\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"cn4\" value=\"\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"card_end_month\" value=\"\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"card_end_year\" value=\"\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"card_pw\" value=\"\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"card_jumin1\" value=\"\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"card_jumin2\" value=\"\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"cardCheckYn\" id=\"cardCheckYn\" value=\"N\">\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("<!-- 추가한 인풋 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD><div class=\"buy_title\"><img src=\"/images/common/5.gif\">&nbsp;&nbsp;주문상품</div></TD>\r\n");
      out.write("\t</TR>\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD>\r\n");
      out.write("\t\t\t<TABLE width=\"800\" cellspacing=\"0\" >\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<TD width=\"30px\" bgcolor=\"#eeeeee\" height= \"40px\"  style=\"border-bottom: 1px solid #c0c0c0;border-top: 1px solid #c0c0c0;\"><INPUT type=\"checkbox\" name=\"selectAll\" onclick=\"allCheck()\" checked></TD>\r\n");
      out.write("\t\t\t\t\t<TD width=\"100px\" bgcolor=\"#eeeeee\" height= \"40px\" style=\"border-bottom: 1px solid #c0c0c0;border-top: 1px solid #c0c0c0\">상품 이미지</TD>\r\n");
      out.write("\t\t\t\t\t<TD width=\"200px\" bgcolor=\"#eeeeee\" height= \"40px\" style=\"border-bottom: 1px solid #c0c0c0;border-top: 1px solid #c0c0c0\">상품명</TD>\r\n");
      out.write("\t\t\t\t\t<TD width=\"100px\" bgcolor=\"#eeeeee\" height= \"40px\" style=\"border-bottom: 1px solid #c0c0c0;border-top: 1px solid #c0c0c0\">수량</TD>\r\n");
      out.write("\t\t\t\t\t<TD width=\"100px\" bgcolor=\"#eeeeee\" height= \"40px\" style=\"border-bottom: 1px solid #c0c0c0;border-top: 1px solid #c0c0c0\">단품 가격</TD>\r\n");
      out.write("\t\t\t\t\t<TD width=\"100px\" bgcolor=\"#eeeeee\" height= \"40px\" style=\"border-bottom: 1px solid #c0c0c0;border-top: 1px solid #c0c0c0\">구매 금액</TD>\r\n");
      out.write("\t\t\t\t\t<TD width=\"100px\" bgcolor=\"#eeeeee\" height= \"40px\" style=\"border-bottom: 1px solid #c0c0c0;border-top: 1px solid #c0c0c0\">삭제</TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");

	if (shoppingCartList.size() == 0)
	{

      out.write("\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<TD colspan=\"7\" align=\"center\" valign=\"middle\" height=\"50\"> 장바구니에 등록된 물품이 없습니다.</TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");

	}
	else
	{
		int wholPrice = 0;
		ArrayList goodsBuyList = new ArrayList();
		Hashtable goodsBuyTable = new Hashtable();
		for (int i = 0; i < shoppingCartList.size(); i++)
		{
			goodsBuyList = (ArrayList)shoppingCartList.get(i);
			goodsBuyTable = (Hashtable)goodsBuyList.get(0);

			String goodsName = (String)goodsBuyTable.get("NAME");
			String code = (String)goodsBuyTable.get("GOODS_CODE");
			if (code == null)
			{
				code = (String)goodsBuyTable.get("CODE");
			}
			String amount = (String)goodsBuyTable.get("GOODS_AMOUNT");
			String parPrice = (String)goodsBuyTable.get("PAR_PRICE");//판매가
			String imgPath = (String)goodsBuyTable.get("PATH");
			String imgName = (String)goodsBuyTable.get("SAVE_NAME");
			String img = imgPath + "/" + imgName;

			img = img.substring(img.indexOf("upfile"));

			int totalPrice = Integer.parseInt(amount) * Integer.parseInt(parPrice);
			wholPrice = wholPrice + totalPrice;
			
			/*
			if (amount.equals("0"))
			{
				amountKo = "품절";
			}
			else
			{
				amountKo = "재고있음";
			}

			checkItem,name,zipcode1,zipcode2,addr1,addr2,home1,home2,home3,mobile1,mobile2,mobile3,office1,office2,office3,
			cn1,cn2,cn3,cn4,month,year,
			*/

      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<INPUT type=\"hidden\" name=\"code\" value=\"");
      out.print(code);
      out.write("\">\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<TD><INPUT class=\"checkboxSelect\" type=\"checkbox\" name=\"checkItem\" id=\"checkItem\" value=\"");
      out.print(code);
      out.write("\" checked></TD>\r\n");
      out.write("\t\t\t\t\t<TD><img src=");
      out.print(img);
      out.write(" width=\"100\" height=\"100\"></TD>\r\n");
      out.write("\t\t\t\t\t<TD>");
      out.print(goodsName);
      out.write("</TD>\r\n");
      out.write("\t\t\t\t\t<TD><INPUT type=\"text\" name=\"amount\" value = ");
      out.print(amount);
      out.write(" size=\"1\"></TD>\r\n");
      out.write("\t\t\t\t\t<TD><SPAN id=\"parPrice\">");
      out.print(parPrice);
      out.write("</SPAN></TD>\r\n");
      out.write("\t\t\t\t\t<TD><SPAN id=\"totalPrice\">");
      out.print(totalPrice);
      out.write("</SPAN></TD>\r\n");
      out.write("\t\t\t\t\t<TD><INPUT type=\"button\" value=\"delete\" onclick=\"deleteAction('");
      out.print(code);
      out.write("');\"></TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<TR><TD colspan=\"7\"><hr noshade color=\"#eeeeee\"></TD></TR>\r\n");

		}

      out.write("\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<TD width=\"700\" bgcolor=\"#eeeeee\" colspan=\"6\"></TD>\r\n");
      out.write("\t\t\t\t\t<TD width=\"100\" bgcolor=\"#eeeeee\"><B>총 금액 : <SPAN id=\"totalPrice\">");
      out.print(wholPrice);
      out.write("</SPAN></B></TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<TR><TD colspan=\"7\" height=\"30\"></TD></TR>\r\n");

	}
	Hashtable userInfoTable = (Hashtable)userInfoList.get(0);
	String name = (String)userInfoTable.get("NAME");
	String zipCode1 = (String)userInfoTable.get("ZIPCODE1");
	String zipCode2 = (String)userInfoTable.get("ZIPCODE2");
	String addr1 = (String)userInfoTable.get("ADDR1");
	String addr2 = (String)userInfoTable.get("ADDR2");

	if (addr2 == "" || addr2 == null)
	{
		addr2 = "";
	}

	String home1 = (String)userInfoTable.get("HOME1");
	String home2 = (String)userInfoTable.get("HOME2");
	String home3 = (String)userInfoTable.get("HOME3");
	String office1 = (String)userInfoTable.get("OFFICE1");
	String office2 = (String)userInfoTable.get("OFFICE2");
	String office3 = (String)userInfoTable.get("OFFICE3");
	String mobile1 = (String)userInfoTable.get("MOBILE1");
	String mobile2 = (String)userInfoTable.get("MOBILE2");
	String mobile3 = (String)userInfoTable.get("MOBILE3");

	if (home1.equals("000"))
	{
		home2 = "";
		home3 = "";
	}
	else if (office1.equals("000"))
	{
		office2 = "";
		office3 = "";
	}
	else if (mobile1.equals("000"))
	{
		mobile2 = "";
		mobile3 = "";
	}

      out.write("\r\n");
      out.write("\t\t\t</TABLE>\r\n");
      out.write("\t\t</TD>\r\n");
      out.write("\t</TR>\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD>\r\n");
      out.write("\t\t\t<TABLE width=\"800\" cellspacing=\"0\" >\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<TD><div class=\"buy_title\"><img src=\"/images/common/5.gif\">&nbsp;&nbsp;배송지 입력</div></TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<TR><TD><hr noshade color=\"#eeeeee\"></TD></TR>\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<TABLE>\r\n");
      out.write("\t\t\t\t\t\t<FORM name=\"addrSelect\">\r\n");
      out.write("\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t배송지 선택\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<INPUT type=\"radio\" name=\"shoppingAddress\" id=\"shoppingAddress\" value=\"defaultAddr\" onclick=\"addrChange()\" checked>&nbsp;&nbsp;기본 배송지&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<INPUT type=\"radio\" name=\"shoppingAddress\"  id=\"shoppingAddress\" value=\"newAddr\"  onclick=\"addrChange()\">&nbsp;&nbsp;새로운 배송지\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t배송비 선택\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<INPUT type=\"radio\" name=\"inventorySelect\" id=\"inventorySelect\" value=\"Y\" onclick=\"inventoryChange()\" checked>&nbsp;&nbsp;선불&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<INPUT type=\"radio\" name=\"inventorySelect\"  id=\"inventorySelect\" value=\"N\"  onclick=\"inventoryChange()\">&nbsp;&nbsp;착불&nbsp;&nbsp; <SPAN id=\"inventory\" style=\"\"> [<font color=\"red\">선불</font>은 배송비로 2,500원이 추가됩니다.]</SPAN>\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t</FORM>\r\n");
      out.write("\t\t\t\t\t\t</TABLE>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t<TABLE name=\"defaultAddrTable\" id=\"defaultAddrTable\" style=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<FORM name=\"defaultAddrForm\">\r\n");
      out.write("\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t받으시는 분\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<INPUT type=\"text\" name=\"name\" value=\"");
      out.print(name);
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD rowspan=\"3\"  align=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t배송지\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<INPUT type=\"text\" name=\"zipCode1\" value=\"");
      out.print(zipCode1);
      out.write("\" size=\"1\" readonly> - <INPUT type=\"text\" name=\"zipCode2\" value=\"");
      out.print(zipCode2);
      out.write("\" size=\"1\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<INPUT type=\"text\" name=\"addr1\" value=\"");
      out.print(addr1);
      out.write("\" size=\"35\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<INPUT type=\"text\" name=\"addr2\" value=\"");
      out.print(addr2);
      out.write("\" size=\"35\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t휴대전화\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<SELECT name=\"mobile1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"000\" ");
if(mobile1.equals("000")){
      out.write("selected");
}
      out.write(">--선택--</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"010\" ");
if(mobile1.equals("010")){
      out.write("selected");
}
      out.write(">010</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"011\" ");
if(mobile1.equals("011")){
      out.write("selected");
}
      out.write(">011</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"016\" ");
if(mobile1.equals("016")){
      out.write("selected");
}
      out.write(">016</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"017\" ");
if(mobile1.equals("017")){
      out.write("selected");
}
      out.write(">017</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"018\" ");
if(mobile1.equals("018")){
      out.write("selected");
}
      out.write(">018</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"019\" ");
if(mobile1.equals("019")){
      out.write("selected");
}
      out.write(">019</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</SELECT>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t- <INPUT type=\"text\" name=\"mobile2\" maxlength=\"4\" size=\"5\" value=\"");
      out.print(mobile2);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t- <INPUT type=\"text\" name=\"mobile3\" maxlength=\"4\" size=\"5\" value=\"");
      out.print(mobile3);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t집전화\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<SELECT name=\"home1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"000\" ");
if(home1.equals("000")){
      out.write("selected");
}
      out.write(">--선택--</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"02\"  ");
if(home1.equals("02")){
      out.write("selected");
}
      out.write(">02</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"031\" ");
if(home1.equals("031")){
      out.write("selected");
}
      out.write(">031</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"032\" ");
if(home1.equals("032")){
      out.write("selected");
}
      out.write(">032</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"033\" ");
if(home1.equals("033")){
      out.write("selected");
}
      out.write(">033</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"041\" ");
if(home1.equals("041")){
      out.write("selected");
}
      out.write(">041</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"042\" ");
if(home1.equals("042")){
      out.write("selected");
}
      out.write(">042</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"043\" ");
if(home1.equals("043")){
      out.write("selected");
}
      out.write(">043</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"051\" ");
if(home1.equals("051")){
      out.write("selected");
}
      out.write(">051</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"052\" ");
if(home1.equals("052")){
      out.write("selected");
}
      out.write(">052</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"053\" ");
if(home1.equals("053")){
      out.write("selected");
}
      out.write(">053</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"054\" ");
if(home1.equals("054")){
      out.write("selected");
}
      out.write(">054</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"055\" ");
if(home1.equals("055")){
      out.write("selected");
}
      out.write(">055</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"061\" ");
if(home1.equals("061")){
      out.write("selected");
}
      out.write(">061</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"062\" ");
if(home1.equals("062")){
      out.write("selected");
}
      out.write(">062</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"063\" ");
if(home1.equals("063")){
      out.write("selected");
}
      out.write(">063</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"064\" ");
if(home1.equals("064")){
      out.write("selected");
}
      out.write(">064</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</SELECT>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t- <INPUT type=\"text\" name=\"home2\" maxlength=\"4\" size=\"5\" value=\"");
      out.print(home2);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t- <INPUT type=\"text\" name=\"home3\" maxlength=\"4\" size=\"5\" value=\"");
      out.print(home3);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t직장전화\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<SELECT name=\"office1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"000\" ");
if(office1.equals("000")){
      out.write("selected");
}
      out.write(">--선택--</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"02\"  ");
if(office1.equals("02")){
      out.write("selected");
}
      out.write(">02</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"031\" ");
if(office1.equals("031")){
      out.write("selected");
}
      out.write(">031</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"032\" ");
if(office1.equals("032")){
      out.write("selected");
}
      out.write(">032</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"033\" ");
if(office1.equals("033")){
      out.write("selected");
}
      out.write(">033</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"041\" ");
if(office1.equals("041")){
      out.write("selected");
}
      out.write(">041</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"042\" ");
if(office1.equals("042")){
      out.write("selected");
}
      out.write(">042</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"043\" ");
if(office1.equals("043")){
      out.write("selected");
}
      out.write(">043</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"051\" ");
if(office1.equals("051")){
      out.write("selected");
}
      out.write(">051</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"052\" ");
if(office1.equals("052")){
      out.write("selected");
}
      out.write(">052</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"053\" ");
if(office1.equals("053")){
      out.write("selected");
}
      out.write(">053</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"054\" ");
if(office1.equals("054")){
      out.write("selected");
}
      out.write(">054</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"055\" ");
if(office1.equals("055")){
      out.write("selected");
}
      out.write(">055</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"061\" ");
if(office1.equals("061")){
      out.write("selected");
}
      out.write(">061</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"062\" ");
if(office1.equals("062")){
      out.write("selected");
}
      out.write(">062</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"063\" ");
if(office1.equals("063")){
      out.write("selected");
}
      out.write(">063</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"064\" ");
if(office1.equals("064")){
      out.write("selected");
}
      out.write(">064</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</SELECT>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t- <INPUT type=\"text\" name=\"office2\" maxlength=\"4\" size=\"5\" value=\"");
      out.print(office2);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t- <INPUT type=\"text\" name=\"office3\" maxlength=\"4\" size=\"5\" value=\"");
      out.print(office3);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>배송시 요청사항</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD><TEXTAREA name=\"comment\" rows=\"4\" cols=\"35\"></TEXTAREA></TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t</FORM>\r\n");
      out.write("\t\t\t\t\t\t</TABLE>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<TABLE name=\"newAddrTable\" id=\"newAddrTable\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t\t\t<FORM name=\"newAddrForm\">\r\n");
      out.write("\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t받으시는 분\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<INPUT type=\"text\" name=\"newBuyMember\" value=\"\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD rowspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t배송지\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<INPUT type=\"text\" name=\"newZipCode1\" size=\"1\" value=\"\"> - <INPUT type=\"text\" name=\"newZipCode1\" size=\"1\" value=\"\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<INPUT type=\"text\" name=\"newAddr1\" size=\"35\" value=\"\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<INPUT type=\"text\" name=\"newAddr2\" size=\"35\" value=\"\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t휴대전화\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<SELECT name=\"newMobile1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"000\">--선택--</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"010\">010</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"011\">011</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"016\">016</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"017\">017</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"018\">018</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"019\">019</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</SELECT>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t- <INPUT type=\"text\" name=\"newMobile2\" maxlength=\"4\" size=\"5\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t- <INPUT type=\"text\" name=\"newMobile3\" maxlength=\"4\" size=\"5\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t집전화\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<SELECT name=\"newHome1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"000\">--선택--</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"02\" >02</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"031\">031</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"032\">032</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"033\">033</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"041\">041</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"042\">042</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"043\">043</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"051\">051</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"052\">052</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"053\">053</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"054\">054</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"055\">055</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"061\">061</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"062\">062</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"063\">063</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"064\">064</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</SELECT>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t- <INPUT type=\"text\" name=\"newHome2\" maxlength=\"4\" size=\"5\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t- <INPUT type=\"text\" name=\"newHome3\" maxlength=\"4\" size=\"5\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t직장전화\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<SELECT name=\"newOffice1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"000\">--선택--</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"02\">02</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"031\">031</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"032\">032</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"033\">033</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"041\">041</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"042\">042</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"043\">043</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"051\">051</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"052\">052</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"053\">053</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"054\">054</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"055\">055</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"061\">061</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"062\">062</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"063\">063</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=\"064\">064</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</SELECT>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t- <INPUT type=\"text\" name=\"newOffice2\" maxlength=\"4\" size=\"5\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t- <INPUT type=\"text\" name=\"newOffice3\" maxlength=\"4\" size=\"5\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>배송시 요청사항</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD><TEXTAREA name=\"newComment\" rows=\"4\" cols=\"35\"></TEXTAREA></TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t</FORM>\r\n");
      out.write("\t\t\t\t\t\t</TABLE>\r\n");
      out.write("\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t</TABLE>\r\n");
      out.write("\t\t</TD>\r\n");
      out.write("\t</TR>\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD colspan=\"7\" height=\"20\" bgcolor=\"#eeeeee\" style=\"border-bottom: 1px solid #c0c0c0;border-top: 1px solid #c0c0c0\"></TD>\r\n");
      out.write("\t</TR>\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD>\r\n");
      out.write("\t\t\t<TABLE width=\"800\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t<TR><TD height=\"30\"></TD></TR>\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<TD><div class=\"buy_title\"><img src=\"/images/common/5.gif\">&nbsp;&nbsp;결재 방법</div></TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t<TABLE cellspacing=\"0\" cellpadding=\"0\" width=\"800\" border=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t<FORM name=\"payWayForm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"radio\" id =\"card\" name=\"payway\" value=\"card\"  onclick=\"payWayChoice();\" checked>&nbsp;신용카드 결재 &nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" id =\"cash\" name=\"payway\" value=\"cash\"  onclick=\"payWayChoice();\">&nbsp;무통장 입금\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</TABLE>\r\n");
      out.write("\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<TD height=\"15\">\r\n");
      out.write("\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t<TABLE cellspacing=\"0\" cellpadding=\"0\" width=\"800\" bgcolor=\"#FFFFFF\" id=\"payCard\" style=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<FORM name=\"payByCardForm\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"100\"> 카드 번호 </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" size=\"4\" name=\"cn1\" id=\"cn1\" maxlength=\"4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t- <input type=\"text\" size=\"4\" name=\"cn2\" id=\"cn2\" maxlength=\"4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t- <input type=\"text\" size=\"4\" name=\"cn3\" id=\"cn3\" maxlength=\"4\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t- <input type=\"text\" size=\"4\" name=\"cn4\" id=\"cn4\" maxlength=\"4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"100\"> 유효 기간 </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<SELECT name=\"card_end_month\" id=\"card_end_month\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										for(int i =0 ; i<12; i++)
										{
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=");
      out.print( i+1);
      out.write('>');
      out.print( i+1);
      out.write("</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>&nbsp;월\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<SELECT name=\"card_end_year\" id=\"card_end_year\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										for(int j =2013 ; j<2024; j++)
										{
									
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION value=");
      out.print( j);
      out.write('>');
      out.print( j);
      out.write("</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>&nbsp;년\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"100\"> 비밀 번호 </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"password\" size=\"4\"  name=\"card_pw\" id=\"card_pw\" maxlength=\"4\"  >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>주민 번호</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<INPUT type=\"text\" name=\"card_jumin1\" size=\"9\" maxlength=\"6\" id=\"card_jumin1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t- <INPUT type=\"password\" name=\"card_jumin2\" size=\"13\" maxlength=\"7\" id=\"card_jumin2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width> 할부 기간 </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class =\"cardPeriod\" name=\"cardPeriod\" value=\"일시불\" size=\"5\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<INPUT type=\"button\" value=\"카드검사\" onclick=\"cardCheckAction();\"> <SPAN id =\"cardCheckMessage\"></SPAN>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<TR><TD height=\"10\"></TD>\r\n");
      out.write("\t\t\t\t\t\t\t</FORM>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t<!----------------------------- 무통장 결제 선택시  ----------------------->\r\n");
      out.write("\t\t\t\t\t\t<table id=\"payCashInfo\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>아래 계좌로 입금해 주십시오.</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<TR><TD height=\"15\"></TD></TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<TABLE>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>결재금액 </td> <td><SPAN id=\"totalPrice\"></SPAN></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td> 입 금 은 행 </td> <td> 국민은행</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td> 계 좌 번 호 </td> <td> 0000-000-000000</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td> 예 금 주 명 </td> <td> 영남상사</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td> 입 금 자 명 </td> <td> ㅁㄴㄹㅇ!!!!</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td> 결 제 금 액 </td> <td>  adsasd원</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TR><TD height=\"10\"></TD></TR>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"구매하기\" id=\"pay\" onclick=\"buyAction();\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"취소하기\" id=\"cancle\" onclick=\"GoCancle();\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t</TABLE>\r\n");
      out.write("\t\t</TD>\r\n");
      out.write("\t</TR>\r\n");
      out.write("\t</FORM>\r\n");
      out.write("</TABLE>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
