/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-06-04 05:50:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.goods;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class ShoppingInterest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      java.util.Hashtable outputTable = null;
      outputTable = (java.util.Hashtable) _jspx_page_context.getAttribute("outputTable", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (outputTable == null){
        outputTable = new java.util.Hashtable();
        _jspx_page_context.setAttribute("outputTable", outputTable, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');

	ArrayList shoppingInterestList = (ArrayList)outputTable.get("shoppingInterestList");

	String id = (String)session.getAttribute("id");
	String loginYn = "N";
	if(session.getAttribute("loginYn")!=null && ((String)session.getAttribute("loginYn")).equals("Y"))
	{
		loginYn = "Y";
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<SCRIPT>\r\n");
      out.write("\t//장바구니에 상품등록\r\n");
      out.write("\tfunction goodsCartAction(code)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif ('");
      out.print(loginYn);
      out.write("' == 'N')\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif (confirm(\"로그인이 필요한 메뉴입니다. \\n로그인하시겠습니까?\"))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tdocument.location.href=\"/memberServlet.mo?func=member_004\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar amount = window.prompt(\"담을 수량을 입력하세요~!\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (amount==null)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.location.href=\"/goodsServlet.mo?func=goods_004&amount=\"+amount+\"&code=\"+code;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//상품 상세보기\r\n");
      out.write("\tfunction viewAction(code)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar f = document.shoppingInterestListForm;\r\n");
      out.write("\t\tf.func.value = \"goods_002\";\r\n");
      out.write("\t\tf.code.value = code;\r\n");
      out.write("\t\tf.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction deleteAction(code)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.location.href=\"/goodsServlet.mo?func=goods_CDH003&code=\"+code;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div><!-- 관심상품 화면 상단 바 -->\r\n");
      out.write("\t<img src=\"/images/cart_wish/t_wish.png\">\r\n");
      out.write("</div>\r\n");
      out.write("<span style=\"margin-left:30px;\">현제 페이지 : <A href=\"/goodsServlet.mo?func=goods_001\">홈</A>>관심상품\r\n");
      out.write("<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t<tr><td colspan=\"2\" height=\"20\"></td></tr>\r\n");
      out.write("\t<tr> \r\n");
      out.write("\t\t<td width=\"10\"><img src=\"/images/common/bul_02_01.gif\"></td>\r\n");
      out.write("\t\t<td class=\"font16_title\"><font color=\"333333\"><B>위시리스트</B></font></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<hr color=\"#eeeeee\" noshade>\r\n");
      out.write("\r\n");
      out.write("<div id=\"interestWrap\" class=\"text\">\r\n");
      out.write("\t<TABLE>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD height=\"30\"></TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\"  border=\"0\">\r\n");
      out.write("\t\t<FORM name=\"shoppingInterestListForm\" method=\"GET\" action=\"/goodsServlet.mo\">\r\n");
      out.write("\t\t\t<INPUT type=\"hidden\" name=\"func\" value=\"goods_002\">\r\n");
      out.write("\t\t\t<INPUT type=\"hidden\" name=\"code\">\r\n");
      out.write("\t\t\t<INPUT type=\"hidden\" name=\"from\" value=\"wish_list\">\r\n");

	int count = shoppingInterestList.size();
	if (count == 0)
	{

      out.write("\r\n");
      out.write("\t\t<TR><td align=\"center\">등록된 상품이 없습니다.</td></TR>\r\n");

	}
	else
	{
		int loopNum1 = count/4;
		if(count%4 != 0)
		{
			loopNum1 = loopNum1 + 1;
		}

		for(int i=0; i<loopNum1; i++)
		{

      out.write("\r\n");
      out.write("\t\t<tr>\r\n");

			for(int j=0; j<4; j++)
			{
				int getNum = (i * 4) + j;

				if(getNum < count)
				{
					Hashtable shoppingInterestTable = (Hashtable)shoppingInterestList.get(getNum);

					String name = (String)shoppingInterestTable.get("NAME");
					String parPrice = (String)shoppingInterestTable.get("PAR_PRICE");
					String code = (String)shoppingInterestTable.get("CODE");
					String quantity = (String)shoppingInterestTable.get("QUANTITY");

					ArrayList goodsImgList = (ArrayList)shoppingInterestTable.get("FILE_LIST");
					Hashtable goodsImgTable = (Hashtable)goodsImgList.get(0);
					String path = (String)goodsImgTable.get("PATH");
					String saveName = (String)goodsImgTable.get("SAVE_NAME");
					
					path = "/"+path.substring(path.indexOf("upfile"));
				/*	
					System.out.println("파일경로 : "+path+"/"+saveName);
				
					for(int imsi = 0; imsi<goodsImgList.size() ; imsi++)
					{
						System.out.println("이미지리스트"+imsi+" : "+goodsImgList.get(imsi)+"\n\n");
					}
				*/


      out.write("\r\n");
      out.write("\t\t\t\t\t<TD width=\"210\">\r\n");
      out.write("\t\t\t\t\t<div class=\"goodsDiv\">\r\n");
      out.write("\t\t\t\t\t\t<TABLE class=\"goodsList\" width=\"190\" height=\"270\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<IMG src=\"");
      out.print(path+"/"+saveName);
      out.write("\" width=\"150\" height=\"150\" style=\"cursor:pointer\" onclick=\"javascript:viewAction('");
      out.print(code);
      out.write("')\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<FONT size=2 color=\"#0066ff\"><B>");
      out.print(name);
      out.write("</B></FONT>\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<FONT size=2>");
      out.print(quantity);
      out.write("</FONT>\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<FONT size=2 color=\"#666666\"><B>");
      out.print(parPrice);
      out.write(" 원</B></FONT>\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t\t\t</TABLE>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"addcart_bt\" onclick=\"goodsCartAction('");
      out.print(code);
      out.write("');\">\r\n");
      out.write("\t\t\t\t\t\t장바구니 담기\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"addcart_bt\" onclick=\"deleteAction('");
      out.print(code);
      out.write("');\">\r\n");
      out.write("\t\t\t\t\t\t관심상품 제거\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</TD>\r\n");

				}
				else
				{

      out.write("\r\n");
      out.write("\t\t\t\t\t<TD width=\"190\"></TD>\r\n");

				}
			}
		}
	}

      out.write("\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t</FORM>\r\n");
      out.write("\t<!--프로그램 종료-->\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
