/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-06-05 07:18:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manager.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class GoodsAddInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      java.util.Hashtable outputTable = null;
      outputTable = (java.util.Hashtable) _jspx_page_context.getAttribute("outputTable", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (outputTable == null){
        outputTable = new java.util.Hashtable();
        _jspx_page_context.setAttribute("outputTable", outputTable, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");

		System.out.println("test sub jsp========");
		ArrayList ItemSelectList = (ArrayList)outputTable.get("ItemSelectList");
		ArrayList SubSelectList =(ArrayList)outputTable.get("SubSelectList");

			
		Hashtable subTable =new Hashtable();
		Hashtable itemTable = new Hashtable();

		String maincategory = (String)outputTable.get("maincategory");
		
		String middlecategory =(String)outputTable.get("middlecategory");
	
		System.out.println("middlecategory1 ===="+middlecategory);
		String code ="";
		if(ItemSelectList.size() !=0)
		{
			
		    itemTable = (Hashtable)ItemSelectList.get(0);
			maincategory = (String)itemTable.get("MAIN_CATEGORY");

		}


      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("td\r\n");
      out.write("  {\r\n");
      out.write("\t height:25px;\r\n");
      out.write("\t color:white;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" </style>\r\n");
      out.write("<SCRIPT language=\"JavaScript\">\r\n");
      out.write("\r\n");
      out.write("//상품 등록\r\n");
      out.write("\tfunction updateAction()\r\n");
      out.write("\t{\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\talert(\"action\");\r\n");
      out.write("\r\n");
      out.write("\t\tvar f = document.itemForm;\r\n");
      out.write("\t\tvar middlecategory = f.middlecategory.value;\r\n");
      out.write("\t\tvar subcategory = f.subcategory.value;\r\n");
      out.write("\t\tvar image1 = f.upFile1.value;\r\n");
      out.write("\t\tvar image2 = f.upFile2.value;\r\n");
      out.write("\t\tvar image3 = f.upFile3.value;\r\n");
      out.write("\t\tvar name = f.name.value;\r\n");
      out.write("\t\tvar orgPrice = f.orgPrice.value;\r\n");
      out.write("\t\tvar parPrice = f.parPrice.value;\r\n");
      out.write("\t\tvar country = f.country.value;\r\n");
      out.write("\t\tvar company = f.company.value;\r\n");
      out.write("\t\tvar goodsComment = f.goodsComment.value;\r\n");
      out.write("\t\tvar quantity = f.quantity.value;\r\n");
      out.write("\t\tvar goodsAmount = f.goodsAmount.value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (middlecategory.length < 3)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"중분류를 선택해주세요!\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (subcategory.length < 3)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"소분류를 선택해주세요!\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (image1 == null && image2 == null && image3 == null)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"이미지를 등록하세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (name.length == 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"상품 이름을 입력해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (orgPrice*0 != 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"상품 원가는 숫자로 입력해주세요\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (orgPrice.length == 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"상품 원가를 입력해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (parPrice*0 != 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"상품 판매가는 숫자로 입력해주세요\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (parPrice.length == 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"상품 판매가를 입력해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (country.length == 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"상품 원산지를 입력해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (company.length == 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"상품 제조사를 입력해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (goodsComment.length == 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tf.goodsComment.value = \"empty\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (quantity.length == 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"상품 내용량을 입력해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (goodsAmount*0 != 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"상품 수량은 숫자로 입력해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (goodsAmount.length >3)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"상품 수량은 3자리까지만 입력해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tf.submit();\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction listAction()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.location.href=\"/superManagerServlet.mo?func=superMan_001\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t// 대분류 변경\r\n");
      out.write("\tfunction selectApply(code)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.location.href=\"/managerOrderServlet.mo?func=managerOrder_003&maincategory=\"+code;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//중분류변경\r\n");
      out.write("\tfunction selectApply2()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar f = document.itemForm;\r\n");
      out.write("\t\tvar test = f.middlecategory.value;\r\n");
      out.write("\t\t//alert(test);\r\n");
      out.write("\t\t document.location.href=\"/managerOrderServlet.mo?func=managerOrder_003&middlecategory=\"+test+\"&maincategory=");
      out.print(maincategory);
      out.write("\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 상세정보 페이지 가기\r\n");
      out.write("\tfunction goDetailInfo(seq)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.location.href=\"/managerOrderServlet.mo?func=managerOrder_002&seq=\"+seq;\r\n");
      out.write("\t}\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("<div><!-- 리스트 화면 상단 바 -->\r\n");
      out.write("\t<img src=\"/images/common/t_admin.png\">\r\n");
      out.write("</div>\r\n");
      out.write("<font color=\"#000000\"><span style=\"margin-left:30px;\">현제 페이지 : <A href=\"/goodsServlet.mo?func=goods_001\">홈</A>>관리자페이지</font>\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<CENTER>\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t<TR><TD height=\"25\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"1\" cellpadding=\"5\" bgcolor=\"#74c900\" width=\"550\">\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD align=\"center\" bgcolor=\"#74c900\" width=\"300\" colspan=\"6\">\r\n");
      out.write("\t\t\t\t<FONT color=\"white\" size=\"3\"><B>상품등록</B>\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t<TR><TD height=\"25\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<FORM name=\"itemForm\" action=\"/managerOrderServlet.mo\"   enctype=\"multipart/form-data\" method=\"post\"><!-- post-->\r\n");
      out.write("<INPUT type=\"hidden\" name=\"func\" value=\"managerOrder_004\">\r\n");
      out.write("<INPUT type=\"hidden\" name=\"getFileYn\" value=\"Y\">\r\n");
      out.write("\t<TABLE cellspacing=\"1\" cellpadding=\"4\" bgcolor=\"#a0c0cb\" width=\"550\">\r\n");
      out.write("\t\t<TR bgcolor=\"#74c900\" align=\"center\">\r\n");
      out.write("\t\t\t<TD width=\"100\" height=\"30\"><B>대분류선택</B></TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#FFFFFF\" width=\"100\" align=\"left\" colspan=\"3\"><font color=\"black\">식품<INPUT type=\"radio\" value = \"F\" name=\"maincategory\"  onclick=\"selectApply('F');\" ");
if(maincategory.equals("F")){
      out.write("checked");
}
      out.write("><font color=\"black\">잡화<INPUT type=\"radio\" name=\"maincategory\" onclick=\"selectApply('E');\" value=\"E\" ");
if(maincategory.equals("E")){
      out.write("checked");
}
      out.write("></TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<TR bgcolor=\"#74c900\" align=\"center\">\r\n");
      out.write("\t\t\t<TD width=\"100\" height=\"30\"><B>중분류선택</B></TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#FFFFFF\" width=\"300\" align=\"left\" colspan=\"3\">\r\n");
      out.write("\t\t\t<SELECT name =\"middlecategory\" onchange=\"selectApply2();\" >\r\n");
      out.write("\t\t\t<OPTION value=\"\">---카테고리---</OPTION>\r\n");
		
				
					System.out.println("middlecategory3 ===="+middlecategory);
					for (int i = 0; i<ItemSelectList.size(); i++)
				   {
					
					itemTable = (Hashtable)ItemSelectList.get(i);	
					String middlename = (String)itemTable.get("NAME");
					
					 code = (String)itemTable.get("CODE");
					System.out.println("code==="+code);
				
					
							/////code = 중분류의 번호. middlecategory = subcategory의 middlecategory 번호.

      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<OPTION value=\"");
      out.print(code);
      out.write('"');
      out.write(' ');
if(code.equals(middlecategory)){
      out.write("selected");
}
      out.write('>');
      out.print(middlename);
      out.write("</OPTION>\r\n");
      out.write("\t\t\t\t\r\n");

					}

      out.write("\r\n");
      out.write("\t\t\t</SELECT>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<TR bgcolor=\"#74c900\" align=\"center\">\r\n");
      out.write("\t\t\t<TD width=\"100\" ><B>소분류선택</B></TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#FFFFFF\" width=\"300\" align=\"left\" colspan=\"3\">\r\n");
      out.write("\t\t\t<SELECT name =\"subcategory\" >\r\n");
      out.write("\t\t\t<OPTION value=\"\">---카테고리---</OPTION>\r\n");
		
		
					for (int i = 0; i<SubSelectList.size(); i++)
					{
					 subTable = (Hashtable)SubSelectList.get(i);	
					String subname = (String)subTable.get("NAME");  ////   middle select 의 분류값이 int 로 되어있기 때문에 임시로 name으로 대체하였다.
					String subcode = (String)subTable.get("CODE");

      out.write("\r\n");
      out.write("\t\t\t\t\t<OPTION value=\"");
      out.print(subcode);
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(subname);
      out.write("</OPTION>\r\n");
      out.write("\t\t\t\t\r\n");

					}

      out.write("\r\n");
      out.write("\t\t\t</SELECT>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<TR bgcolor=\"#74c900\" align=\"center\">\r\n");
      out.write("\t\t\t<TD width=\"100\"><B>이미지등록</B></TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#FFFFFF\"  align=\"left\" colspan=\"3\">\r\n");
      out.write("\t\t\t\t<INPUT type=\"file\" name=\"upFile1\" size=\"40\">\r\n");
      out.write("\t\t\t\t<INPUT type=\"file\" name=\"upFile2\" size=\"40\">\r\n");
      out.write("\t\t\t\t<INPUT type=\"file\" name=\"upFile3\" size=\"40\">\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\t\t<TR bgcolor=\"#74c900\" align=\"center\">\r\n");
      out.write("\t\t\t<TD width=\"100\"><B>물품이름</B></TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#FFFFFF\" width=\"300\" align=\"left\" colspan=\"3\"><INPUT type=\"text\" name=\"name\"></TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<TR bgcolor=\"#74c900\" align=\"center\">\r\n");
      out.write("\t\t\t<TD width=\"100\"><B>물품원가</B></TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#FFFFFF\" width=\"300\" align=\"left\" colspan=\"3\"><INPUT type=\"text\" name=\"orgPrice\"></TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR bgcolor=\"#74c900\" align=\"center\">\r\n");
      out.write("\t\t\t<TD width=\"100\"><B>물품 판매가</B></TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#FFFFFF\" width=\"300\" align=\"left\" colspan=\"3\"><INPUT type=\"text\" name=\"parPrice\"></TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<TR bgcolor=\"#74c900\" align=\"center\">\r\n");
      out.write("\t\t\t<TD width=\"100\"><B>원산지</B></TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#FFFFFF\" width=\"300\" align=\"left\" colspan=\"3\"><INPUT type=\"text\" name=\"country\"></TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<TR bgcolor=\"#74c900\" align=\"center\">\r\n");
      out.write("\t\t\t<TD width=\"100\"><B>제조사</B></TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#FFFFFF\" width=\"300\" align=\"left\" colspan=\"3\"><INPUT type=\"text\" name=\"company\"></TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\t\t<TR bgcolor=\"#74c900\" align=\"center\">\r\n");
      out.write("\t\t\t<TD width=\"100\"><B>물품 부가설명</B></TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#FFFFFF\" width=\"300\" align=\"left\" colspan=\"3\"><INPUT type=\"text\" name=\"goodsComment\"></TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\t\t<TR bgcolor=\"#74c900\" align=\"center\">\r\n");
      out.write("\t\t\t<TD width=\"100\"><B>물품 내용량</B></TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#FFFFFF\" width=\"300\" align=\"left\" colspan=\"3\"><INPUT type=\"text\" name=\"quantity\"></TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR bgcolor=\"#74c900\" align=\"center\">\r\n");
      out.write("\t\t\t<TD width=\"100\"><B>물품 수량</B></TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#FFFFFF\" width=\"300\" align=\"left\" colspan=\"3\"><INPUT type=\"text\" name=\"goodsAmount\"></TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("</FORM>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<TABLE cellspacing=\"1\" cellpadding=\"3\" width=\"750\" >\r\n");
      out.write("\t\t<TR><TD height=\"5\"></TD></TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD align=\"center\">\r\n");
      out.write("\t\t\t\t<IMG src=\"/images/button/Update.png\" border=\"0\" onclick=\"updateAction();\" style=\"cursor:hand\" align=\"absmiddle\">\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<IMG src=\"/images/button/List.png\" border=\"0\" onclick=\"listAction();\" style=\"cursor:hand\" align=\"absmiddle\">\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR><TD height=\"3\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\" width=\"700\">\r\n");
      out.write("\t\t<TR><TD height=\"20\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("</CENTER>\r\n");
      out.write("<FORM name=\"addForm\" method=\"post\" action=\"/managerHobbyServlet.mo\" target=\"addHobby\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"func\" value=\"managerHobby_006\">\r\n");
      out.write("</FORM>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
