/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-06-05 06:31:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manager.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class ReturnOrderList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      java.util.Hashtable outputTable = null;
      outputTable = (java.util.Hashtable) _jspx_page_context.getAttribute("outputTable", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (outputTable == null){
        outputTable = new java.util.Hashtable();
        _jspx_page_context.setAttribute("outputTable", outputTable, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      java.util.Hashtable inputTable = null;
      inputTable = (java.util.Hashtable) _jspx_page_context.getAttribute("inputTable", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (inputTable == null){
        inputTable = new java.util.Hashtable();
        _jspx_page_context.setAttribute("inputTable", inputTable, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");

	ArrayList ReturnOrderList = (ArrayList)outputTable.get("ReturnOrderList");
	
	
	String pageType = (String)inputTable.get("pageType");
	Integer articlePerPage = (Integer)inputTable.get("articlePerPage");
	Integer pageNum = (Integer)inputTable.get("pageNum");
	
	Integer pageTotalNum = (Integer)inputTable.get("pageTotalNum");
	Integer articleTotalNum = (Integer)inputTable.get("articleTotalNum");
	

      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("  .R1{\r\n");
      out.write(" \r\n");
      out.write("   border-left: 1px solid #cfdee9;\r\n");
      out.write("   border-bottom:1px solid #e4e4e4;\r\n");
      out.write("  }\r\n");
      out.write(" \r\n");
      out.write(" .R2{\r\n");
      out.write("\t\tborder-top:1px solid #e4e4e4;\r\n");
      out.write("\t\r\n");
      out.write("\t  }\r\n");
      out.write("  .R3{\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("   border-bottom:1px solid #e4e4e4;\r\n");
      out.write("  }\r\n");
      out.write(".R4{\r\n");
      out.write(" \r\n");
      out.write("\t\r\n");
      out.write("  border-left: 1px solid #cfdee9;\r\n");
      out.write("   border-top:1px solid #e4e4e4;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" td\r\n");
      out.write("  {\r\n");
      out.write("\t height:25px;\r\n");
      out.write("\t color:white;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write(" </style>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT language=\"JavaScript\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t// 상세정보 페이지 가기\r\n");
      out.write("\tfunction goDetailInfo(code,state)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.location.href=\"/managerOrderServlet.mo?func=managerOrder_020&code=\"+code+\"&state=\"+state;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("<div><!-- 리스트 화면 상단 바 -->\r\n");
      out.write("\t<img src=\"/images/common/t_admin.png\">\r\n");
      out.write("</div>\r\n");
      out.write("<span style=\"margin-left:30px;\">현제 페이지 : <A href=\"/goodsServlet.mo?func=goods_001\">홈</A>>관리자페이지\r\n");
      out.write("<CENTER>\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t<TR><TD height=\"25\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"1\" cellpadding=\"5\" bgcolor=\"#74c900\" width=\"850\">\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD align=\"center\" bgcolor=\"#74c900\" width=\"400\" >\r\n");
      out.write("\t\t\t\t<FONT color=\"white\" size=\"3\"><B>반품신청 리스트</FONT></B>\t\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<BR>\r\n");
      out.write("\t<FORM name=\"ReturnForm\" action=\"/managerOrderServlet.mo\" method=\"post\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"func\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"seq\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"hit\">\r\n");
      out.write("\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"pageNum\" value=\"");
      out.print( pageNum);
      out.write("\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"pageType\" value=\"");
      out.print( pageType);
      out.write("\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"articlePerPage\" value=\"");
      out.print( articlePerPage);
      out.write("\">\r\n");
      out.write("</FORM>\r\n");
      out.write("\r\n");
      out.write("\t<TABLE cellspacing=\"1\" cellpadding=\"4\" bgcolor=\"#74c900\" width=\"850\" >\r\n");
      out.write("\t\t<TR bgcolor=\"#74c900\" align=\"center\">\r\n");
      out.write("\t\t\t<TD width=\"150\" height=\"30\"><B>글 번호</B></TD>\r\n");
      out.write("\t\t\t<TD width=\"150\" ><B>주문일자</B></TD>\r\n");
      out.write("\t\t\t<TD width=\"150\"><B>상품명</B></TD>\r\n");
      out.write("\t\t\t<TD width=\"150\"><B>결제금액</B></TD>\r\n");
      out.write("\t\t\t<TD width=\"150\"><B>계좌번호</B></TD>\r\n");
      out.write("\t\t\t<TD width=\"150\"><B>반품상태</B></TD>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</TR>\r\n");

	if(ReturnOrderList==null || ReturnOrderList.size()==0)
	{

      out.write("\r\n");
      out.write("\t\t<TR><TD align=\"center\" bgcolor=\"#FFFFFF\" colspan=\"6\"><font color=\"black\"><B>주문 정보가 없습니다.</B></font></TD></TR>\r\n");

	}
	else
	{
		String startNum = (String)((Hashtable)ReturnOrderList.get(0)).get("DISP_NUM");
		String endNum = (String)((Hashtable)ReturnOrderList.get(ReturnOrderList.size()-1)).get("DISP_NUM");

		for(int i=0; i<ReturnOrderList.size(); i++)
		{
			Hashtable orderTable = (Hashtable)ReturnOrderList.get(i);
			String dispNum = (String)orderTable.get("DISP_NUM");
			String returnDate = (String)orderTable.get("REQUEST_DATE");
			String state = (String)orderTable.get("RETURN_STATE");
			String code = (String)orderTable.get("CODE");
			String name = (String)orderTable.get("NAME");
			String account = (String)orderTable.get("ACCOUNT_NUM");
			String price=(String)orderTable.get("PRICE");
			
			System.out.println("code if문"+code);

			String bgcolor = "#FFFFFF";

			
			String useState = "";
		

	////////////////////////여기서 E는 사용자가 반품신청했을때 등록되는 최초값이다. ///////////////////////
			if(state.equals("E"))
			{
				useState="반품요청";
			}
			else if(state.equals("T"))
			{
				useState="물품확인";
			}

			else if(state.equals("B"))
			{
				useState="반품완료";
			}
			else if(state.equals("F"))
			{
				useState="환불완료";
			}
		



      out.write("\r\n");
      out.write("\t\t<TR bgcolor=\"");
      out.print( bgcolor);
      out.write("\" align=\"center\" >\r\n");
      out.write("\t\t<TD align=\"center\"  ><FONT color=\"black\">");
      out.print( dispNum);
      out.write("</FONT></TD>\r\n");
      out.write("\t\t\t<TD   height=\"20\"><FONT color=\"black\"><A href=\"javascript:goDetailInfo('");
      out.print( code);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(state);
      out.write("')\">");
      out.print( returnDate);
      out.write("</A></FONT></TD>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<TD  ><FONT color=\"black\">");
      out.print( name);
      out.write("</FONT></TD>\r\n");
      out.write("\t\t\t<TD  ><FONT color=\"black\">");
      out.print( price);
      out.write("</FONT></TD>\r\n");
      out.write("\t\t\t<TD  ><FONT color=\"black\">");
      out.print( account);
      out.write("</FONT></TD>\r\n");
      out.write("\t\t\t<TD  ><FONT color=\"black\">");
      out.print( useState);
      out.write("</FONT></TD>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</TR>\r\n");

		}
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\" width=\"750\">\r\n");
      out.write("\t\t<TR><TD height=\"10\"></TD></TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD width=\"750\">\r\n");
      out.write("\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/manager/admin/ReturnOrderPageNumber.jsp", out, true);
      out.write("\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR><TD height=\"30\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("</CENTER>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
