/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-06-04 05:28:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manager.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class SubCategoryUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      java.util.Hashtable outputTable = null;
      outputTable = (java.util.Hashtable) _jspx_page_context.getAttribute("outputTable", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (outputTable == null){
        outputTable = new java.util.Hashtable();
        _jspx_page_context.setAttribute("outputTable", outputTable, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");

	ArrayList SubInfoList = (ArrayList)outputTable.get("SubInfoList");
	Hashtable categoryTable = (Hashtable)SubInfoList.get(0);

	//String from = (String)inputTable.get("from");

	String code = (String)categoryTable.get("CODE");
	String useYn = (String)categoryTable.get("USEYN");
	String maincategory = (String)categoryTable.get("MAIN_CATEGORY");
	String middleCategory_name = (String)categoryTable.get("MIDDLE_CATEGORY_NAME");
	String middleCategory_code = (String)categoryTable.get("MIDDLE_CATEGORY");
	String useMainText = "";

	System.out.println("여기는 섭카테고리 업뎃 code : "+code);

	if(maincategory.equals("F"))
	{
		useMainText ="식품";
	}
	else
	{
		useMainText="잡화";
	}

	
	
	String useKor = "사용중";
	if(useYn.equals("N"))
	{
		useKor = "미사용";
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("  td\r\n");
      out.write("  {\r\n");
      out.write("\t height:25px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write(" </style>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT language=\"JavaScript\">\r\n");
      out.write("\t// 직업 목록 페이지 가기\r\n");
      out.write("\tfunction goList()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.location.href=\"/managerHobbyServlet.mo?func=managerHobby_001\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 직업 수정 취소 버튼\r\n");
      out.write("\tfunction cancelAction()\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"");
      out.print(code);
      out.write("\");\r\n");
      out.write("\t\tdocument.location.href=\"/managerOrderServlet.mo?func=managerOrder_017&code=");
      out.print(code);
      out.write("\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 직업 수정\r\n");
      out.write("\tfunction updateAction()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar f = document.updateForm;\r\n");
      out.write("\t\tif(trim(f.name.value)==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"직업의 이름을 입력하세요.\");\r\n");
      out.write("\t\t\tf.name.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\talert(\"submit 전\");\r\n");
      out.write("\t\tf.name.value = trim(f.name.value);\r\n");
      out.write("\t\tf.submit();\r\n");
      out.write("\t}\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<CENTER>\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t<TR><TD height=\"25\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"1\" cellpadding=\"5\" bgcolor=\"#74c900\" width=\"250\">\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD align=\"center\" bgcolor=\"#74c900\" width=\"250\">\r\n");
      out.write("\t\t\t\t<FONT color=\"white\" size=\"3\"><B>카테고리 수정</B></FONT></FONT>\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\" width=\"600\">\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD align=\"right\">\r\n");
      out.write("\t\t\t\t<IMG src=\"/images/button/button_all_list.gif\" border=\"0\" onclick=\"goList();\" style=\"cursor:hand\" align=\"absmiddle\" onClick=\"goList();\">\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR><TD height=\"3\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"1\" cellpadding=\"4\" bgcolor=\"#74c900\" width=\"600\">\r\n");
      out.write("\t\t<FORM name=\"updateForm\" method=\"post\" action=\"/managerOrderServlet.mo\" onSubmit=\"updateAction(); return false;\">\r\n");
      out.write("\t\t\t<INPUT type=\"hidden\" name=\"func\" value=\"managerOrder_016\">\r\n");
      out.write("\t\t\t<INPUT type=\"hidden\" name=\"code\" value=\"");
      out.print( code);
      out.write("\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD width=\"150\" bgcolor=\"#74c900\" align=\"center\"><FONT color=\"white\"><B>CODE</B></FONT></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\">");
      out.print( code);
      out.write("</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#74c900\" align=\"center\"><FONT color=\"white\"><B>상품 분류</B></FONT></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\" width=\"100\" align=\"left\">식품<INPUT type=\"radio\" value = \"F\" name=\"maincategory\" ");
if(maincategory.equals("F")){
      out.write("checked");
}
      out.write(">잡화<INPUT type=\"radio\" name=\"maincategory\" value=\"E\" ");
if(maincategory.equals("E")){
      out.write("checked");
}
      out.write("></TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#74c900\" align=\"center\"><FONT color=\"white\"><B>상품 중분류</B></FONT></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\" width=\"100\" align=\"left\">\r\n");
      out.write("\t\t\t\t<SELECT name =\"middlecategory\">\r\n");
      out.write("\t\t\t\t\t<OPTION value=\"blank\">---카테고리---</OPTION>\r\n");

					ArrayList ItemSelectList = (ArrayList)outputTable.get("ItemSelectList");

					for (int i = 0; i<ItemSelectList.size(); i++)
					{
					
						Hashtable itemTable = (Hashtable)ItemSelectList.get(i);	
						String middlename = (String)itemTable.get("NAME");
						
						String middle_code = (String)itemTable.get("CODE");
						System.out.println("middle_code==="+middle_code+"\n"+middleCategory_code);
				
					
						////code = 중분류의 번호. middlecategory = subcategory의 middlecategory 번호.

      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"");
      out.print(middle_code);
      out.write('"');
      out.write(' ');
if(middle_code.equals(middleCategory_code) ){
      out.write("selected");
}
      out.write('>');
      out.print(middlename);
      out.write("</OPTION>\r\n");
      out.write("\t\t\t\t\r\n");

					}

      out.write("\r\n");
      out.write("\t\t\t\t</SELECT>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#74c900\" align=\"center\"><FONT color=\"white\"><B>NAME</B></FONT></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\"><INPUT type=\"text\" name=\"name\" value=\"");
      out.print( categoryTable.get("NAME"));
      out.write("\"></TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#74c900\" align=\"center\"><FONT color=\"white\"><B>사용 여부</B></FONT></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\">\r\n");
      out.write("\t\t\t\t\t<SELECT name=\"yn\">\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"Y\" ");
if(useYn.equals("Y")){
      out.write("selected");
}
      out.write(">사용</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"N\" ");
if(useYn.equals("N")){
      out.write("selected");
}
      out.write(">미사용</OPTION>\r\n");
      out.write("\t\t\t\t\t</SELECT>\r\n");
      out.write("\t\t\t\t</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#74c900\" align=\"center\"><FONT color=\"white\"><B>작성자 (IP)</B></FONT></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\">");
      out.print( categoryTable.get("REG_ID"));
      out.write(' ');
      out.write('(');
      out.print( categoryTable.get("REG_IP"));
      out.write(")</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#74c900\" align=\"center\"><FONT color=\"white\"><B>작성일</B></FONT></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\">");
      out.print( categoryTable.get("REG_DATE"));
      out.write("</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#74c900\" align=\"center\"><FONT color=\"white\"><B>최종 수정자 (IP)</B></FONT></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\">");
      out.print( categoryTable.get("UPD_ID"));
      out.write(' ');
      out.write('(');
      out.print( categoryTable.get("UPD_IP"));
      out.write(")</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#74c900\" align=\"center\"><FONT color=\"white\"><B>최종 수정일</B></FONT></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\">");
      out.print( categoryTable.get("UPD_DATE"));
      out.write("</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t</FORM>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\" width=\"700\">\r\n");
      out.write("\t\t<TR><TD height=\"5\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\" width=\"700\">\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD align=\"center\">\r\n");
      out.write("\t\t\t\t<IMG src=\"/images/button/but_update.gif\" border=\"0\" align=\"absmiddle\" alt=\"수정\" style=\"cursor:hand\" onClick=\"updateAction();\">\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<IMG src=\"/images/button/but_cancel1.gif\" border=\"0\" align=\"absmiddle\" alt=\"취소\" style=\"cursor:hand\" onClick=\"cancelAction();\">\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\" width=\"700\">\r\n");
      out.write("\t\t<TR><TD height=\"20\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("</CENTER>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
