/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-05-15 13:33:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manager.bbs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class BbsInfoView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      java.util.Hashtable outputTable = null;
      outputTable = (java.util.Hashtable) _jspx_page_context.getAttribute("outputTable", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (outputTable == null){
        outputTable = new java.util.Hashtable();
        _jspx_page_context.setAttribute("outputTable", outputTable, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");

	ArrayList bbsInfoViewList = (ArrayList)outputTable.get("bbsInfoViewList");
	Hashtable bbsInfoTable = (Hashtable)bbsInfoViewList.get(0);

	String code = (String)bbsInfoTable.get("CODE");
	String useYn = (String)bbsInfoTable.get("USE_YN");
	String perPage = (String)bbsInfoTable.get("PER_PAGE");
	String searchYn = (String)bbsInfoTable.get("SEARCH_YN");
	String replyYn = (String)bbsInfoTable.get("REPLY_YN");
	String replySort = (String)bbsInfoTable.get("REPLY_SORT");
	String addYn = (String)bbsInfoTable.get("ADD_YN");
	String addSort = (String)bbsInfoTable.get("ADD_SORT");
	String updateYn = (String)bbsInfoTable.get("UPDATE_YN");
	String numberType = (String)bbsInfoTable.get("NUMBER_TYPE");
	String fileYn = (String)bbsInfoTable.get("FILE_YN");
	String regId = (String)bbsInfoTable.get("REG_ID");
	String regDate = (String)bbsInfoTable.get("REG_DATE");
	String regIp = (String)bbsInfoTable.get("REG_IP");
	String updId = (String)bbsInfoTable.get("UPD_ID");
	String updDate = (String)bbsInfoTable.get("UPD_DATE");
	String updIp = (String)bbsInfoTable.get("UPD_IP");

	String useKor = "사용중";
	if(useYn.equals("N"))
	{
		useKor = "미사용";
	}

	String searchKor = "사용중";
	if(searchYn.equals("N"))
	{
		searchKor = "미사용";
	}

	String replyKor = "사용중";
	if(replyYn.equals("N"))
	{
		replyKor = "미사용";
	}

	String addKor = "사용중";
	if(addYn.equals("N"))
	{
		addKor = "미사용";
	}

	String updateKor = "작성 및 수정 가능";
	if(updateYn.equals("N"))
	{
		updateKor = "글 보기만 가능";
	}

	String numberKor = "10페이지 단위로 표시";
	if(numberType.equals("C"))
	{
		numberKor = "현재 페이지를 항상 가운데 표시";
	}

	String replySortKor = "최근 답글 우선 정렬";
	if(replySort.equals("STEP"))
	{
		replySortKor = "작성 순서로 정렬";
	}

	String addSortKor = "작성 순서로 정렬";
	if(addSort.equals("DESC"))
	{
		addSortKor = "최근 댓글 우선 정렬";
	}

	String fileKor = "사용중";
	if(fileYn.equals("N"))
	{
		fileKor = "미사용";
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<SCRIPT language=\"JavaScript\">\r\n");
      out.write("\t// 취미 목록 페이지 가기\r\n");
      out.write("\tfunction goList()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.location.href=\"/managerBbsServlet.mo?func=managerBbs_001\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 취미 수정 페이지 가기\r\n");
      out.write("\tfunction goUpdate()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.location.href='/managerBbsServlet.mo?func=managerBbs_005&from=info&code=");
      out.print( code);
      out.write("';\r\n");
      out.write("\t}\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<CENTER>\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t<TR><TD height=\"25\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"1\" cellpadding=\"5\" bgcolor=\"#7682EB\" width=\"250\">\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD align=\"center\" bgcolor=\"#CFDDFA\" width=\"250\">\r\n");
      out.write("\t\t\t\t<FONT color=\"blue\" size=\"3\"><B>게시판 상세 정보</B></FONT>\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\" width=\"600\">\r\n");
      out.write("\t\t<TR><TD height=\"20\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"1\" cellpadding=\"4\" bgcolor=\"#7682EB\" width=\"700\">\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD width=\"150\" bgcolor=\"#CFDDFA\" align=\"center\"><B>게시판 이름</B></TD>\r\n");
      out.write("\t\t\t<TD width=\"550\" bgcolor=\"#FFFFFF\" colspan=\"3\">");
      out.print( bbsInfoTable.get("NAME"));
      out.write("</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD width=\"150\" bgcolor=\"#CFDDFA\" align=\"center\"><B>CODE</B></TD>\r\n");
      out.write("\t\t\t<TD width=\"200\" bgcolor=\"#FFFFFF\">");
      out.print( code);
      out.write("</TD>\r\n");
      out.write("\t\t\t<TD width=\"150\" bgcolor=\"#CFDDFA\" align=\"center\"><B>사용 여부</B></TD>\r\n");
      out.write("\t\t\t<TD width=\"200\" bgcolor=\"#FFFFFF\">");
      out.print( useKor);
      out.write("</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#CFDDFA\" align=\"center\"><B>출력 개수</B></TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#FFFFFF\"><B>");
      out.print( perPage);
      out.write("</B> 개씩 출력</TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#CFDDFA\" align=\"center\"><B>쓰기 권한</B></TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#FFFFFF\">");
      out.print( updateKor);
      out.write("</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#CFDDFA\" align=\"center\"><B>검색 기능</B></TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#FFFFFF\">");
      out.print( searchKor);
      out.write("</TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#CFDDFA\" align=\"center\"><B>Page Number Type</B></TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#FFFFFF\">");
      out.print( numberKor);
      out.write("</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#CFDDFA\" align=\"center\"><B>답글 기능</B></TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#FFFFFF\">");
      out.print( replyKor);
      out.write("</TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#CFDDFA\" align=\"center\"><B>답글 정렬</B></TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#FFFFFF\">");
      out.print( replySortKor);
      out.write("</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#CFDDFA\" align=\"center\"><B>댓글 기능</B></TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#FFFFFF\">");
      out.print( addKor);
      out.write("</TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#CFDDFA\" align=\"center\"><B>댓글 정렬</B></TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#FFFFFF\">");
      out.print( addSortKor);
      out.write("</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#CFDDFA\" align=\"center\"><B>첨부 파일 기능</B></TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#FFFFFF\">");
      out.print( fileKor);
      out.write("</TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#CFDDFA\" align=\"center\"><B></B></TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#FFFFFF\"></TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#CFDDFA\" align=\"center\"><B>작성자 (IP)</B></TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#FFFFFF\">");
      out.print( regId);
      out.write(' ');
      out.write('(');
      out.print( regIp);
      out.write(")</TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#CFDDFA\" align=\"center\"><B>작성일시</B></TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#FFFFFF\">");
      out.print( regDate);
      out.write("</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#CFDDFA\" align=\"center\"><B>최종 수정자 (IP)</B></TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#FFFFFF\">");
      out.print( updId);
      out.write(' ');
      out.write('(');
      out.print( updIp);
      out.write(")</TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#CFDDFA\" align=\"center\"><B>최종 수정일시</B></TD>\r\n");
      out.write("\t\t\t<TD bgcolor=\"#FFFFFF\">");
      out.print( updDate);
      out.write("</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\" width=\"700\">\r\n");
      out.write("\t\t<TR><TD height=\"10\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\" width=\"700\">\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD align=\"center\">\r\n");
      out.write("\t\t\t\t<IMG src=\"/images/button/but_update.gif\" border=\"0\" align=\"absmiddle\" alt=\"수정\" style=\"cursor:hand\" onClick=\"goUpdate();\">\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<IMG src=\"/images/button/but_ok.gif\" border=\"0\" align=\"absmiddle\" alt=\"취소\" style=\"cursor:hand\" onClick=\"goList();\">\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\" width=\"700\">\r\n");
      out.write("\t\t<TR><TD height=\"20\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("</CENTER>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
