/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-06-04 05:49:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manager.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class UserUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      java.util.Hashtable outputTable = null;
      outputTable = (java.util.Hashtable) _jspx_page_context.getAttribute("outputTable", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (outputTable == null){
        outputTable = new java.util.Hashtable();
        _jspx_page_context.setAttribute("outputTable", outputTable, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      java.util.Hashtable inputTable = null;
      inputTable = (java.util.Hashtable) _jspx_page_context.getAttribute("inputTable", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (inputTable == null){
        inputTable = new java.util.Hashtable();
        _jspx_page_context.setAttribute("inputTable", inputTable, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");

	ArrayList interestList = (ArrayList)outputTable.get("interestList");

	ArrayList userInfoList = (ArrayList)outputTable.get("userInfoList");
	Hashtable userInfoTable = (Hashtable)userInfoList.get(0);
	String id = (String)userInfoTable.get("ID");
	String pass = (String)userInfoTable.get("PASS");
	String passQ_code = (String)userInfoTable.get("PASS_Q");
	String passA = (String)userInfoTable.get("PASS_A");
	String name = (String)userInfoTable.get("NAME");
	String jumin1 = (String)userInfoTable.get("JUMIN1");
	String jumin2 = (String)userInfoTable.get("JUMIN2");
	String home1 = (String)userInfoTable.get("HOME1");
	String home2 = (String)userInfoTable.get("HOME2");
	String home3 = (String)userInfoTable.get("HOME3");
	String office1 = (String)userInfoTable.get("OFFICE1");
	String office2 = (String)userInfoTable.get("OFFICE2");
	String office3 = (String)userInfoTable.get("OFFICE3");
	String mobile1 = (String)userInfoTable.get("MOBILE1");
	String mobile2 = (String)userInfoTable.get("MOBILE2");
	String mobile3 = (String)userInfoTable.get("MOBILE3");
	String zipCode1 = (String)userInfoTable.get("ZIPCODE1");
	String zipCode2 = (String)userInfoTable.get("ZIPCODE2");
	String addr1 = (String)userInfoTable.get("ADDR1");
	String addr2 = (String)userInfoTable.get("ADDR2");
	String email = (String)userInfoTable.get("EMAIL");
	String interest = (String)userInfoTable.get("INTEREST");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<SCRIPT language=\"JavaScript\">\r\n");
      out.write("\t// 회원정보 수정\r\n");
      out.write("\tfunction updateAction()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar f = document.joinForm;\r\n");
      out.write("\r\n");
      out.write("\t\t// 비밀번호 값 체크\r\n");
      out.write("\t\tif(f.pass1.value==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("\t\t\tf.pass1.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(f.pass1.value.length<4 || f.pass1.value.length>21)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"비밀번호는 4자 이상 20자 이하로 입력하세요.\");\r\n");
      out.write("\t\t\tf.pass1.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(isEngNum(f.pass1.value))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"비밀번호는 숫자 또는 영문 소문자만 가능합니다.\");\r\n");
      out.write("\t\t\tf.pass1.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(f.pass1.value != f.pass2.value)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"비밀번호를 확인하여 주십시오.\");\r\n");
      out.write("\t\t\tf.pass2.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tf.pass1.value = trim(f.pass1.value);\r\n");
      out.write("\r\n");
      out.write("\t\t// 전화번호 체크\r\n");
      out.write("\t\tvar telCheck = 3;\r\n");
      out.write("\t\tif(f.home1.value==\"000\" && trim(f.home2.value)==\"\" && trim(f.home3.value)==\"\" )\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\ttelCheck--;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(f.home1.value==\"000\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\twindow.alert(\"집 전화 지역번호를 선택하여 주십시오.\");\r\n");
      out.write("\t\t\t\tf.home1.focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(trim(f.home2.value)==\"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\twindow.alert(\"집 전화 국번을 입력하여 주십시오.\");\r\n");
      out.write("\t\t\t\tf.home2.select();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(f.home2.value.length<3)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\twindow.alert(\"집 전화 국번을 바르게 입력하여 주십시오.\");\r\n");
      out.write("\t\t\t\tf.home2.select();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(!isNum(f.home2.value))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\twindow.alert(\"전화 번호는 숫자로 입력바랍니다.\");\r\n");
      out.write("\t\t\t\tf.home2.select();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(trim(f.home3.value)==\"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\twindow.alert(\"집 전화 끝자리 번호를 입력하여 주십시오.\");\r\n");
      out.write("\t\t\t\tf.home3.select();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(f.home3.value.length<4)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\twindow.alert(\"집 전화 끝자리 번호를 바르게 입력하여 주십시오.\");\r\n");
      out.write("\t\t\t\tf.home3.select();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(!isNum(f.home3.value))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\twindow.alert(\"전화 번호는 숫자로 입력바랍니다.\");\r\n");
      out.write("\t\t\t\tf.home3.select();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(f.office1.value==\"000\" && trim(f.office2.value)==\"\" && trim(f.office3.value)==\"\" )\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\ttelCheck--;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(f.office1.value==\"000\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\twindow.alert(\"직장 전화 지역번호를 선택하여 주십시오.\");\r\n");
      out.write("\t\t\t\tf.office1.focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(trim(f.office2.value)==\"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\twindow.alert(\"직장 전화 국번을 입력하여 주십시오.\");\r\n");
      out.write("\t\t\t\tf.office2.select();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(f.office2.value.length<3)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\twindow.alert(\"직장 전화 국번을 바르게 입력하여 주십시오.\");\r\n");
      out.write("\t\t\t\tf.office2.select();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(!isNum(f.office2.value))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\twindow.alert(\"전화 번호는 숫자로 입력바랍니다.\");\r\n");
      out.write("\t\t\t\tf.office2.select();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(trim(f.office3.value)==\"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\twindow.alert(\"직장 전화 끝자리 번호를 입력하여 주십시오.\");\r\n");
      out.write("\t\t\t\tf.office3.select();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(f.office3.value.length<4)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\twindow.alert(\"직장 전화 끝자리 번호를 바르게 입력하여 주십시오.\");\r\n");
      out.write("\t\t\t\tf.office3.select();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(!isNum(f.office3.value))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\twindow.alert(\"전화 번호는 숫자로 입력바랍니다.\");\r\n");
      out.write("\t\t\t\tf.office3.select();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(f.mobile1.value==\"000\" && trim(f.mobile2.value)==\"\" && trim(f.mobile3.value)==\"\" )\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\ttelCheck--;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(f.mobile1.value==\"000\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\twindow.alert(\"휴대 전화 첫째자리를 선택하여 주십시오.\");\r\n");
      out.write("\t\t\t\tf.mobile1.focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(trim(f.mobile2.value)==\"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\twindow.alert(\"휴대 전화 두째자리를 입력하여 주십시오.\");\r\n");
      out.write("\t\t\t\tf.mobile2.select();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(f.mobile2.value.length<3)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\twindow.alert(\"휴대 전화 두째자리를 바르게 입력하여 주십시오.\");\r\n");
      out.write("\t\t\t\tf.mobile2.select();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(!isNum(f.mobile2.value))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\twindow.alert(\"전화 번호는 숫자로 입력바랍니다.\");\r\n");
      out.write("\t\t\t\tf.mobile2.select();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(trim(f.mobile3.value)==\"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\twindow.alert(\"휴대 전화 끝자리 번호를 입력하여 주십시오.\");\r\n");
      out.write("\t\t\t\tf.mobile3.select();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(f.mobile3.value.length<4)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\twindow.alert(\"휴대 전화 끝자리 번호를 바르게 입력하여 주십시오.\");\r\n");
      out.write("\t\t\t\tf.mobile3.select();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(!isNum(f.mobile3.value))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\twindow.alert(\"전화 번호는 숫자로 입력바랍니다.\");\r\n");
      out.write("\t\t\t\tf.mobile3.select();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(telCheck==0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"집, 직장, 휴대 전화 중 최소 하나이상은 입력해야 합니다.\");\r\n");
      out.write("\t\t\tf.home1.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// 우편번호 체크\r\n");
      out.write("\t\tif(f.zipCode1.value==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"우편번호를 검색하여 입력하세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// 주소 체크\r\n");
      out.write("\t\tif(trim(f.addr2.value)==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"상세주소를 입력하세요.\");\r\n");
      out.write("\t\t\tf.addr2.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tf.addr2.value = trim(f.addr2.value);\r\n");
      out.write("\r\n");
      out.write("\t\t// 이메일 체크\r\n");
      out.write("\t\tif(trim(f.email.value)!=\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(isEmailChar(f.email.value))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\twindow.alert(\"이메일 주소에는 영문 소문자와 숫자, '@', '.' 만이 입력가능합니다.\");\r\n");
      out.write("\t\t\t\tf.email.select();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif((f.email.value).indexOf(\"@\") == -1 || (f.email.value).indexOf(\".\") == -1 || (f.email.value).indexOf(\".\")<(f.email.value).indexOf(\"@\") || isNum((f.email.value).charAt(0)))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\twindow.alert(\"이메일 주소를 확인 하세요.\");\r\n");
      out.write("\t\t\t\tf.email.select();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tf.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 정보수정 취소\r\n");
      out.write("\tfunction cancelAction()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.location.href=\"/managerUserServlet.mo?func=managerUser_002&id=");
      out.print( id);
      out.write("\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 우편번호 검색\r\n");
      out.write("\tfunction searchZipCodeAction()\r\n");
      out.write("\t{\r\n");
      out.write("\t\twindow.open(\"/commonServlet.mo?func=common_001\", \"zipSearchOpen\", \"toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=no, width=420, height=500\");\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function(){\r\n");

	if(!home1.equals("000"))
	{

      out.write("\r\n");
      out.write("\tdocument.joinForm.home1.value = \"");
      out.print( home1);
      out.write("\";\r\n");
      out.write("\tdocument.joinForm.home2.value = \"");
      out.print( home2);
      out.write("\";\r\n");
      out.write("\tdocument.joinForm.home3.value = \"");
      out.print( home3);
      out.write("\";\r\n");

	}

	if(!office1.equals("000"))
	{

      out.write("\r\n");
      out.write("\tdocument.joinForm.office1.value = \"");
      out.print( office1);
      out.write("\";\r\n");
      out.write("\tdocument.joinForm.office2.value = \"");
      out.print( office2);
      out.write("\";\r\n");
      out.write("\tdocument.joinForm.office3.value = \"");
      out.print( office3);
      out.write("\";\r\n");

	}

	if(!mobile1.equals("000"))
	{

      out.write("\r\n");
      out.write("\tdocument.joinForm.mobile1.value = \"");
      out.print( mobile1);
      out.write("\";\r\n");
      out.write("\tdocument.joinForm.mobile2.value = \"");
      out.print( mobile2);
      out.write("\";\r\n");
      out.write("\tdocument.joinForm.mobile3.value = \"");
      out.print( mobile3);
      out.write("\";\r\n");

	}

      out.write("\r\n");
      out.write("\tdocument.joinForm.zipCode1.value = \"");
      out.print( zipCode1);
      out.write("\";\r\n");
      out.write("\tdocument.joinForm.zipCode2.value = \"");
      out.print( zipCode2);
      out.write("\";\r\n");
      out.write("\tdocument.joinForm.addr1.value = \"");
      out.print( addr1);
      out.write("\";\r\n");
      out.write("\tdocument.joinForm.addr2.value = \"");
      out.print( addr2);
      out.write("\";\r\n");

	if(!email.equals("empty"))
	{

      out.write("\r\n");
      out.write("\tdocument.joinForm.email.value = \"");
      out.print( email);
      out.write("\";\r\n");

	}

      out.write("\r\n");
      out.write("});\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("<CENTER>\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t<TR><TD height=\"25\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"1\" cellpadding=\"5\" bgcolor=\"#74c900\" width=\"700\">\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD align=\"center\" bgcolor=\"#74c900\" width=\"250\">\r\n");
      out.write("\t\t\t\t<FONT color=\"white\" size=\"3\"><B>회원 정보 수정</B></FONT>\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<BR>\r\n");
      out.write("\t<TABLE cellspacing=\"1\" cellpadding=\"5\" bgcolor=\"#74c900\" width=\"700\">\r\n");
      out.write("\t\t<FORM name=\"joinForm\" action=\"/managerUserServlet.mo\" method=\"post\" onSubmit=\"return false;\">\r\n");
      out.write("\t\t\t<INPUT type=\"hidden\" name=\"func\" value=\"managerUser_004\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<INPUT type=\"hidden\" name=\"id\" value=\"");
      out.print( id);
      out.write("\">\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD width=\"100\" bgcolor=\"#74c900\" align=\"center\"><font color=\"white\"><B>I D</B></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\" colspan=\"3\">");
      out.print( id);
      out.write("</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#74c900\" align=\"center\"><font color=\"white\"><B>비밀 번호</B></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\" width=\"200\"><INPUT type=\"password\" name=\"pass1\" value=\"");
      out.print(pass);
      out.write("\" maxlength=\"20\"></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#74c900\" align=\"center\" width=\"110\"><font color=\"white\"><B>비밀번호확인</B></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\"><INPUT type=\"password\" name=\"pass2\" value=\"");
      out.print(pass);
      out.write("\" maxlength=\"20\"></TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#74c900\" align=\"center\"><font color=\"white\"><B>비밀번호<BR>확인시 질문</B></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\" colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t<SELECT name=\"passQ\">\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"000\">-----------------선  택------------------</OPTION>\r\n");
      out.write("\t\t\t\t\t\t");

							ArrayList passQList = (ArrayList)outputTable.get("passQList");
							for(int i = 0 ; i<passQList.size(); i++)
							{
								Hashtable passQTable = (Hashtable)passQList.get(i);
								String code = (String)passQTable.get("CODE");
								String passQ = (String)passQTable.get("PASS_Q");
								
								if(code.equals(passQ_code))
								{
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<OPTION value=\"");
      out.print(code);
      out.write("\" selected>");
      out.print(passQ);
      out.write("</OPTION>\r\n");
      out.write("\t\t\t\t\t\t");

								}
								else
								{
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<OPTION value=\"");
      out.print(code);
      out.write('"');
      out.write('>');
      out.print(passQ);
      out.write("</OPTION>\r\n");
      out.write("\t\t\t\t\t\t");

								}
							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</SELECT>\r\n");
      out.write("\t\t\t\t</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#74c900\" align=\"center\"><font color=\"white\"><B>비밀번호<BR>확인시 답변</B></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\" width=\"300\" colspan=\"3\"><INPUT type=\"text\" name=\"passA\" value=\"");
      out.print(passA);
      out.write("\"maxlength=\"40\" size=\"48\"></TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#74c900\" align=\"center\"><font color=\"white\"><B>이 름</B></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\" colspan=\"3\"><B>");
      out.print( name);
      out.write("</B></TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#74c900\" align=\"center\"><font color=\"white\"><B>주민등록번호</B></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\" colspan=\"3\">");
      out.print( jumin1);
      out.write(" - *******</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#74c900\" align=\"center\"><font color=\"white\"><B>집 전화</B></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\" colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t<SELECT name=\"home1\">\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"000\">--선택--</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"02\">02</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"031\">031</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"032\">032</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"033\">033</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"041\">041</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"042\">042</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"043\">043</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"051\">051</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"052\">052</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"053\">053</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"054\">054</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"055\">055</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"061\">061</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"062\">062</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"063\">063</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"064\">064</OPTION>\r\n");
      out.write("\t\t\t\t\t</SELECT>\r\n");
      out.write("\t\t\t\t\t- <INPUT type=\"text\" name=\"home2\" maxlength=\"4\" size=\"5\">\r\n");
      out.write("\t\t\t\t\t- <INPUT type=\"text\" name=\"home3\" maxlength=\"4\" size=\"5\">\r\n");
      out.write("\t\t\t\t</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#74c900\" align=\"center\"><font color=\"white\"><B>직장 전화</B></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\" colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t<SELECT name=\"office1\">\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"000\">--선택--</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"02\">02</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"031\">031</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"032\">032</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"033\">033</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"041\">041</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"042\">042</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"043\">043</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"051\">051</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"052\">052</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"053\">053</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"054\">054</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"055\">055</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"061\">061</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"062\">062</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"063\">063</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"064\">064</OPTION>\r\n");
      out.write("\t\t\t\t\t</SELECT>\r\n");
      out.write("\t\t\t\t\t- <INPUT type=\"text\" name=\"office2\" maxlength=\"4\" size=\"5\">\r\n");
      out.write("\t\t\t\t\t- <INPUT type=\"text\" name=\"office3\" maxlength=\"4\" size=\"5\">\r\n");
      out.write("\t\t\t\t</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#74c900\" align=\"center\"><font color=\"white\"><B>휴대 전화</B></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\" colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t<SELECT name=\"mobile1\">\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"000\">--선택--</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"010\">010</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"011\">011</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"016\">016</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"017\">017</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"018\">018</OPTION>\r\n");
      out.write("\t\t\t\t\t\t<OPTION value=\"019\">019</OPTION>\r\n");
      out.write("\t\t\t\t\t</SELECT>\r\n");
      out.write("\t\t\t\t\t- <INPUT type=\"text\" name=\"mobile2\" maxlength=\"4\" size=\"5\">\r\n");
      out.write("\t\t\t\t\t- <INPUT type=\"text\" name=\"mobile3\" maxlength=\"4\" size=\"5\">\r\n");
      out.write("\t\t\t\t</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#74c900\" align=\"center\"><font color=\"white\"><B>주 소</B></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\" colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t<INPUT type=\"text\" name=\"zipCode1\" size=\"5\" onclick=\"searchZipCodeAction();\" readonly>\r\n");
      out.write("\t\t\t\t\t- <INPUT type=\"text\" name=\"zipCode2\" size=\"5\" onclick=\"searchZipCodeAction();\" readonly>\r\n");
      out.write("\t\t\t\t\t<IMG src=\"/images/button/postcode_search.gif\" border=\"0\" style=\"cursor:hand\" align=\"absmiddle\" onclick=\"searchZipCodeAction();\">\r\n");
      out.write("\t\t\t\t\t<BR>\r\n");
      out.write("\t\t\t\t\t<INPUT type=\"text\" name=\"addr1\" size=\"60\" onclick=\"searchZipCodeAction();\" readonly> (행정구역)\r\n");
      out.write("\t\t\t\t\t<INPUT type=\"text\" name=\"addr2\" size=\"60\"> (번지 및 상세주소)\r\n");
      out.write("\t\t\t\t</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#74c900\" align=\"center\"><font color=\"white\"><B>이메일</B></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\" colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t<INPUT type=\"text\" name=\"email\" size=\"60\">\r\n");
      out.write("\t\t\t\t</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#74c900\" align=\"center\"><font color=\"white\"><B>관심상품</B></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\" colspan=\"3\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t<TABLE width=\"580\">\r\n");

	int loopNum2 = interestList.size()/5;
	if(interestList.size()%5 != 0)
	{
		loopNum2 = loopNum2 + 1;
	}

	for(int i=0; i<loopNum2; i++)
	{

      out.write("\r\n");
      out.write("\t\t\t\t\t\t<TR>\r\n");

		for(int j=0; j<5; j++)
		{
			int getNum = (i * 5) + j;
			if(getNum < interestList.size())
			{
				Hashtable interestTable = (Hashtable)interestList.get(getNum);
				String code = (String)interestTable.get("CODE");
				String interestName = (String)interestTable.get("NAME");

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<TD width=\"115\"><INPUT type=\"checkbox\" name=\"interest\" value=\"");
      out.print( code);
      out.write('"');
      out.write(' ');
if (interest.indexOf(code) != -1){
      out.write("checked");
}
      out.write('>');
      out.write(' ');
      out.print( interestName);
      out.write("</TD>\r\n");

			}
			else
			{

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<TD width=\"115\"></TD>\r\n");

			}
		}

      out.write("\r\n");
      out.write("\t\t\t\t\t\t</TR>\r\n");

	}

      out.write("\r\n");
      out.write("\t\t\t\t\t</TABLE>\r\n");
      out.write("\t\t\t\t</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t</FORM>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\" width=\"700\">\r\n");
      out.write("\t\t<TR><TD height=\"10\"></TD></TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD align=\"center\">\r\n");
      out.write("\t\t\t\t<IMG src=\"/images/button/but_update.gif\" border=\"0\" onclick=\"updateAction();\" style=\"cursor:hand\" align=\"absmiddle\">\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<IMG src=\"/images/button/but_cancel1.gif\" border=\"0\" onclick=\"cancelAction();\" style=\"cursor:hand\" align=\"absmiddle\">\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\" width=\"700\">\r\n");
      out.write("\t\t<TR><TD height=\"20\"></TD></TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("</CENTER>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
