/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-06-05 06:46:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import common.conf.*;
import java.util.*;

public final class LeftMenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      java.util.Hashtable outputTable = null;
      outputTable = (java.util.Hashtable) _jspx_page_context.getAttribute("outputTable", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (outputTable == null){
        outputTable = new java.util.Hashtable();
        _jspx_page_context.setAttribute("outputTable", outputTable, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      java.util.Hashtable inputTable = null;
      inputTable = (java.util.Hashtable) _jspx_page_context.getAttribute("inputTable", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (inputTable == null){
        inputTable = new java.util.Hashtable();
        _jspx_page_context.setAttribute("inputTable", inputTable, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');

//	System.out.println("레프트메뉴 outputTable : "+outputTable);
	String middleCategory = (String)inputTable.get("middleCategory");
	String subcode = (String)inputTable.get("subcode");
	System.out.println("세션 카테고리 : "+session.getAttribute("category"));

      out.write("\r\n");
      out.write("<SCRIPT>\r\n");
      out.write("\tfunction goMenu(func)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.location.href=\"/\"+func;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction submenuAction(subcode, subname)\r\n");
      out.write("\t{\r\n");
      out.write("\t\t//alert(middleCategory);\r\n");
      out.write("\t\t//document.location.href=\"/goodsServlet.mo?func=goods_001?middleCategory=\"+middleCategory+\"\";\r\n");
      out.write("\t\tdocument.location.href=\"/goodsServlet.mo?func=goods_007&middleCategory=");
      out.print(middleCategory);
      out.write("&subcode=\"+subcode+\"&subname=\"+subname+\"\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/*LeftMenu Animation*/\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$('.leftMenu').hover(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t},function(){\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t$('div.leftMenu').mouseover(function(){\r\n");
      out.write("\t\tvar menuDiv = $(this);\r\n");
      out.write("\t\tvar codeInfo = menuDiv.attr(\"subcode_info\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (codeInfo!=null)\r\n");
      out.write("\t\t{\t\t\t\r\n");
      out.write("\t\t\tvar img = $(\".leftMenuImg\");\r\n");
      out.write("\t\t\timg.attr(\"src\", \"/images/left_menu/\"+codeInfo+\".jpg\");\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tmenuDiv.css('backgroundColor',\"#d9ffa4\" );\r\n");
      out.write("\t\tmenuDiv.css('color',\"#4c8706\" );\r\n");
      out.write("\t}).mouseout(function(){\r\n");
      out.write("\t\tvar menuDiv = $(this);\r\n");
      out.write("\t\tmenuDiv.css('backgroundColor',\"#ffffff\" );\r\n");
      out.write("\t\tmenuDiv.css('color',\"#666666\" );\r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$('.leftMenu').hover(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t},function(){\r\n");
      out.write("\t\t$(this).animate({ backgroundColor: \"olive\" }, \"slow\");\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("<div id=\"leftMenuWrap\">\r\n");

	if(session != null && session.getAttribute("loginYn")!=null && ((String)session.getAttribute("loginYn")).equals("Y"))
	{
		//일반 맴버일때 변화를 주고 싶다면 여기

		if(session.getAttribute("adminYn")!=null && ((String)session.getAttribute("adminYn")).equals("Y"))
		{
			//관리자일때 변화를 주고싶다면 여기
	

      out.write("\r\n");
      out.write("<div class=\"leftMenu\" onclick=\"document.location.href='/managerOrderServlet.mo?func=managerOrder_003'\">(관리자)상품등록버튼</div>\r\n");
      out.write("\r\n");


		}
	}

      out.write("\r\n");
      out.write("<TABLE cellspacing=\"0\" cellpadding=\"0\" border=\"0\" valign=\"top\">\r\n");
      out.write("\r\n");

if(((String)session.getAttribute("category")).equals("middle_category"))
	{

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD>\r\n");
      out.write("\t\t\t\t<div class=\"leftMenu\" onclick=\"document.location.href='/goodsServlet.mo?func=goods_001'\">상품 전체 보기</div>\r\n");
      out.write("\t\t</TD>\r\n");
      out.write("\t</TR>\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD width=\"220\" align=\"center\">\r\n");
      out.write("\t\t\t<hr noshade color=\"#eeeeee\">\r\n");
      out.write("\t\t</TD>\r\n");
      out.write("\t</TR>\r\n");
      out.write("\r\n");

	}

	if(session != null && session.getAttribute("loginYn")!=null && ((String)session.getAttribute("loginYn")).equals("Y"))
	{
		//일반 맴버일때 변화를 주고 싶다면 여기

		if(session.getAttribute("adminYn")!=null && ((String)session.getAttribute("adminYn")).equals("Y"))
		{
			//관리자일때 변화를 주고싶다면 여기
		}
	}



	ArrayList superMiddlecategoryList = null;
	if(outputTable.get("superMiddlecategoryList")!=null)
	{
		superMiddlecategoryList = (ArrayList)outputTable.get("superMiddlecategoryList");
	}
	//System.out.println(superMiddlecategoryList);
	if(((String)session.getAttribute("category")).equals("middle_category") && superMiddlecategoryList!= null && superMiddlecategoryList.size() != 0)
	{
		Hashtable superMiddlecategoryInfoTable = null;

		for(int j =0; j<superMiddlecategoryList.size(); j++)
		{
			superMiddlecategoryInfoTable = (Hashtable)superMiddlecategoryList.get(j);

			String useYn = (String)superMiddlecategoryInfoTable.get("USEYN");
			if(useYn.equals("Y"))
			{
				String sub_code = (String)superMiddlecategoryInfoTable.get("CODE");
				String sub_name = (String)superMiddlecategoryInfoTable.get("NAME");

      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD width=\"220\" align=\"center\">\r\n");
      out.write("\t\t\t<div class=\"leftMenu\" subcode_info=\"");
      out.print(sub_code);
      out.write("\" onclick=\"JavaScript:submenuAction('");
      out.print(sub_code);
      out.write("', '");
      out.print(sub_name);
      out.write("');\">");
      out.print( sub_name);
      out.write("</div>\r\n");
      out.write("\t\t</TD>\r\n");
      out.write("\t</TR>\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD height=\"1\" bgcolor=\"#eeeeee\"></TD>\r\n");
      out.write("\t</TR>\r\n");


			}
		}

	
		if(subcode!=null && subcode.length() == 0 )//상단 중분류 눌렀을때의 반응
		{
			Hashtable tempSubTable = (Hashtable)superMiddlecategoryList.get(0);
			String img_code = (String)tempSubTable.get("CODE");
			System.out.println("값이 없을때 체크 : "+img_code);

      out.write("\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD><img class=\"leftMenuImg\" src=\"/images/left_menu/");
      out.print(img_code);
      out.write(".jpg\"></TD>\r\n");
      out.write("\t</TR>\t\r\n");

		}
		else
		{
			

      out.write("\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD><img class=\"leftMenuImg\" src=\"/images/left_menu/");
      out.print(subcode);
      out.write(".jpg\"></TD>\r\n");
      out.write("\t</TR>\t\r\n");

		}
	}
	//고객센터 메뉴
	else if(((String)session.getAttribute("category")).equals("support"))
	{
		ReadConf rc = ReadConf.getReadConf();
		Hashtable confTable = rc.getConfTable();
		ArrayList bbsInfoList = (ArrayList)confTable.get("bbsInfoList");

		for(int i=0; i<bbsInfoList.size(); i++)
		{
			Hashtable bbsInfoTable = (Hashtable)bbsInfoList.get(i);
			String useYn = (String)bbsInfoTable.get("USE_YN");
			if(useYn.equals("Y"))
			{
				String code = (String)bbsInfoTable.get("CODE");
				String name = (String)bbsInfoTable.get("NAME");
				
				if(session.getAttribute("category")!=null && ((String)session.getAttribute("category")).equals("support"))
				{

      out.write("\t\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD width=\"220\" align=\"center\">\r\n");
      out.write("\t\t\t\t<div class=\"leftMenu\" onclick=\"goMenu('supportServlet.mo?func=support_002&code=");
      out.print( code);
      out.write("');\">");
      out.print( name);
      out.write("</div>\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");

				}

			}
		}
	}
	else
	{

      out.write("\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD width=\"220\" align=\"center\">\r\n");
      out.write("\t\t\t\t상단 메뉴를 클릭하시면<br>\r\n");
      out.write("\t\t\t\t세부항목이 나옵니다~!\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");

	}

      out.write("\r\n");
      out.write("</TABLE>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"celler_info\">\r\n");
      out.write("\t<img src=\"/images/left_menu/left_info.jpg\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<iframe width=\"220\" height=\"300\" frameborder=\"0\" scrolling=\"no\" marginheight=\"0\" marginwidth=\"0\" src=\"https://maps.google.com/maps?f=d&amp;source=s_d&amp;saddr=&amp;daddr=37.559879,126.976031&amp;hl=ko&amp;geocode=&amp;sll=37.559884,126.976086&amp;sspn=0.00276,0.005209&amp;mra=mift&amp;mrsp=1&amp;sz=18&amp;ie=UTF8&amp;t=m&amp;start=0&amp;ll=37.559803,126.97556&amp;spn=0.002551,0.002264&amp;z=17&amp;output=embed\"></iframe><br /><small><a href=\"https://maps.google.com/maps?f=d&amp;source=embed&amp;saddr=&amp;daddr=37.559879,126.976031&amp;hl=ko&amp;geocode=&amp;sll=37.559884,126.976086&amp;sspn=0.00276,0.005209&amp;mra=mift&amp;mrsp=1&amp;sz=18&amp;ie=UTF8&amp;t=m&amp;start=0&amp;ll=37.559803,126.97556&amp;spn=0.002551,0.002264&amp;z=17\" style=\"color:#0000FF;text-align:left\">크게 보기</a></small>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
