/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-06-04 05:50:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manager.interest;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class InterestList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      java.util.Hashtable outputTable = null;
      outputTable = (java.util.Hashtable) _jspx_page_context.getAttribute("outputTable", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (outputTable == null){
        outputTable = new java.util.Hashtable();
        _jspx_page_context.setAttribute("outputTable", outputTable, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");

	ArrayList interestList = (ArrayList)outputTable.get("interestList");


      out.write("\r\n");
      out.write("\r\n");
      out.write("<SCRIPT language=\"JavaScript\">\r\n");
      out.write("\t// 정보확인\r\n");
      out.write("\tfunction checkAction()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.location.href=\"/commonServlet.mo\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 상세정보 페이지 가기\r\n");
      out.write("\tfunction goDetailInfo(code)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.location.href=\"/managerInterestServlet.mo?func=managerInterest_002&code=\"+code;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 관심사 수정 페이지 가기\r\n");
      out.write("\tfunction goUpdate(code)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.location.href='/managerInterestServlet.mo?func=managerInterest_004&from=list&code='+code;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 관심사 사용 or 삭제 하기\r\n");
      out.write("\tfunction goUseYn(code, yn)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar alertStr = \"선택하신 관심사를 사용하지 못하게 하시겠습니까?\";\r\n");
      out.write("\t\tif(yn=='Y')\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talertStr = \"선택하신 관심사를 사용 하시겠습니까?\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(confirm(alertStr))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tdocument.location.href=\"/managerInterestServlet.mo?func=managerInterest_003&yn=\"+yn+\"&code=\"+code;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 관심사 추가\r\n");
      out.write("\tfunction goAdd()\r\n");
      out.write("\t{\r\n");
      out.write("\t\twindow.open(\"/common/Progress.jsp\", \"addInterest\", \"toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, width=400, height=200\");\r\n");
      out.write("\t\twindow.name = \"listWin\";\r\n");
      out.write("\t\tdocument.addForm.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("<STYLE>\r\n");
      out.write("td\r\n");
      out.write("{\r\n");
      out.write("\theight:30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</STYLE>\r\n");
      out.write("\r\n");
      out.write("<CENTER>\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t<TR><TD height=\"25\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t<TR><TD height=\"25\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"1\" cellpadding=\"5\" bgcolor=\"#74c900\" width=\"750\">\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD align=\"center\" bgcolor=\"#74c900\" width=\"750\">\r\n");
      out.write("\t\t\t\t<FONT color=\"white\" size=\"3\"><B>관심사 목록</B></FONT>\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\" width=\"750\">\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD align=\"right\">\r\n");
      out.write("\t\t\t\t<IMG src=\"/images/button/button_add.gif\" border=\"0\" onclick=\"goAdd();\" style=\"cursor:hand\" align=\"absmiddle\">\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR><TD height=\"3\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"1\" cellpadding=\"4\" bgcolor=\"#74c900\" width=\"750\">\r\n");
      out.write("\t\t<TR bgcolor=\"#74c900\" align=\"center\">\r\n");
      out.write("\t\t\t<TD width=\"100\"><FONT color=\"white\"><B>CODE</B></FONT></TD>\r\n");
      out.write("\t\t\t<TD><FONT color=\"white\"><B>NAME</B></FONT></TD>\r\n");
      out.write("\t\t\t<TD width=\"100\"><FONT color=\"white\"><B>작 성 자</B></FONT></TD>\r\n");
      out.write("\t\t\t<TD width=\"100\"><FONT color=\"white\"><B>최종수정자</B></FONT></TD>\r\n");
      out.write("\t\t\t<TD width=\"100\"><FONT color=\"white\"><B>사용 여부</B></FONT></TD>\r\n");
      out.write("\t\t\t<TD width=\"100\"><FONT color=\"white\"><B>기 능</B></FONT></TD>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t</TR>\r\n");

	for(int i=0; i<interestList.size(); i++)
	{
		Hashtable interestTable = (Hashtable)interestList.get(i);
		String code = (String)interestTable.get("CODE");
		String name = (String)interestTable.get("NAME");
		String regId = (String)interestTable.get("REG_ID");
		String updId = (String)interestTable.get("UPD_ID");
		String useYn = (String)interestTable.get("USEYN");

		String bgcolor = "#FFFFFF";
		if(useYn.equals("N"))
		{
			bgcolor = "#E0E0E0";
		}

		String useKor = "사용중";
		if(useYn.equals("N"))
		{
			useKor = "미사용";
		}

      out.write("\r\n");
      out.write("\t\t<TR bgcolor=\"");
      out.print( bgcolor);
      out.write("\" align=\"center\">\r\n");
      out.write("\t\t\t<TD><A href=\"javascript:goDetailInfo('");
      out.print( code);
      out.write("')\">");
      out.print( code);
      out.write("</A></TD>\r\n");
      out.write("\t\t\t<TD><A href=\"javascript:goDetailInfo('");
      out.print( code);
      out.write("')\">");
      out.print( name);
      out.write("</A></TD>\r\n");
      out.write("\t\t\t<TD>");
      out.print( regId);
      out.write("</TD>\r\n");
      out.write("\t\t\t<TD>");
      out.print( updId);
      out.write("</TD>\r\n");
      out.write("\t\t\t<TD><B>");
      out.print( useKor);
      out.write("</B></TD>\r\n");
      out.write("\t\t\t<TD>\r\n");
      out.write("\t\t\t\t<IMG src=\"/images/button/sbut_update.gif\" align=\"absmiddle\" border=\"0\" style=\"cursor:hand\" onClick=\"goUpdate('");
      out.print( code);
      out.write("')\">\r\n");

		if(useYn.equals("Y"))
		{

      out.write("\r\n");
      out.write("\t\t\t\t<IMG src=\"/images/button/sbut_delete.gif\" align=\"absmiddle\" border=\"0\" style=\"cursor:hand\" onClick=\"goUseYn('");
      out.print( code);
      out.write("', 'N');\">\r\n");

		}
		else
		{

      out.write("\r\n");
      out.write("\t\t\t\t<IMG src=\"/images/button/sbut_use.gif\" align=\"absmiddle\" border=\"0\" style=\"cursor:hand\" onClick=\"goUseYn('");
      out.print( code);
      out.write("', 'Y');\">\r\n");

		}

      out.write("\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");

	}

	if(interestList.size()==0)
	{

      out.write("\r\n");
      out.write("\t\t<TR><TD align=\"center\" bgcolor=\"#FFFFFF\" colspan=\"6\"><B>설정된 관심사 정보가 없습니다.</B></TD></TR>\r\n");

	}

      out.write("\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\" width=\"750\">\r\n");
      out.write("\t\t<TR><TD height=\"5\"></TD></TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD align=\"center\">\r\n");
      out.write("\t\t\t\t<IMG src=\"/images/button/but_ok.gif\" border=\"0\" onclick=\"checkAction();\" style=\"cursor:hand\" align=\"absmiddle\">\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR><TD height=\"3\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\" width=\"700\">\r\n");
      out.write("\t\t<TR><TD height=\"20\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("</CENTER>\r\n");
      out.write("<FORM name=\"addForm\" method=\"post\" action=\"/managerInterestServlet.mo\" target=\"addInterest\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"func\" value=\"managerInterest_006\">\r\n");
      out.write("</FORM>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
