/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-06-05 06:09:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.support;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import support.*;

public final class supportUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      java.util.Hashtable outputTable = null;
      outputTable = (java.util.Hashtable) _jspx_page_context.getAttribute("outputTable", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (outputTable == null){
        outputTable = new java.util.Hashtable();
        _jspx_page_context.setAttribute("outputTable", outputTable, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      java.util.Hashtable inputTable = null;
      inputTable = (java.util.Hashtable) _jspx_page_context.getAttribute("inputTable", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (inputTable == null){
        inputTable = new java.util.Hashtable();
        _jspx_page_context.setAttribute("inputTable", inputTable, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	ArrayList supportViewList = (ArrayList)outputTable.get("supportViewList");

	Hashtable supportTable = (Hashtable)supportViewList.get(0);

	String seq = (String)supportTable.get("SEQ");
	String title = (String)supportTable.get("TITLE");
	String hitCnt = (String)supportTable.get("HIT_CNT");
	String regDate = (String)supportTable.get("REG_DATE");
	String updDate = (String)supportTable.get("UPD_DATE");
	String regId = (String)supportTable.get("REG_ID");
	String regName = (String)supportTable.get("NAME");
	String content = (String)supportTable.get("CONTENT");
	
	boolean loginYn = false;
	boolean writerYn = false;
	boolean adminYn = false;
	if(session != null && session.getAttribute("loginYn")!=null && ((String)session.getAttribute("loginYn")).equals("Y"))
	{
		loginYn = true;
	}
	if(loginYn && regId.equals((String)session.getAttribute("id")))
	{
		writerYn = true;
	}
	if(loginYn && ((String)session.getAttribute("adminYn")).equals("Y"))
	{
		adminYn = true;
	}

	String code = (String)inputTable.get("code");
	SupportInfomation si = new SupportInfomation(code);
	String bbsName = si.getName();

	String pageNum = (String)inputTable.get("pageNum");
	String section = (String)inputTable.get("section");
	String word = (String)inputTable.get("word");

	ArrayList supportFileList = new ArrayList();
	if(si.getFileYn())
	{
		supportFileList = (ArrayList)supportTable.get("FILE_LIST");
	}

	ArrayList supportAddList = new ArrayList();
	if(si.getAddYn())
	{
		supportAddList = (ArrayList)outputTable.get("supportAddList");
	}

	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<SCRIPT language=\"JavaScript\">\r\n");
      out.write("\tfunction updateAction()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar f = document.updateForm;\r\n");
      out.write("\t\tif(trim(f.title.value)==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"제목을 입력하세요\");\r\n");
      out.write("\t\t\tf.title.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(trim(f.content.value)==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"본문을 입력하세요\");\r\n");
      out.write("\t\t\tf.content.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tf.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction listAction()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.bbsForm.func.value=\"support_002\";\r\n");
      out.write("\t\tdocument.bbsForm.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction cancelAction()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.location.href=\"/supportServlet.mo?func=support_005&code=");
      out.print(code);
      out.write("&seq=\"+");
      out.print( seq);
      out.write(";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction fileDownloadAction(svPath, svName, ogName)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar f = document.fileDownloadForm;\r\n");
      out.write("\t\tf.savePath.value = svPath;\r\n");
      out.write("\t\tf.saveName.value = svName;\r\n");
      out.write("\t\tf.orgName.value = ogName;\r\n");
      out.write("\t\tf.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div><!-- 리스트 화면 상단 바 -->\r\n");
      out.write("\t<img src=\"/images/support/t_support.png\">\r\n");
      out.write("</div>\r\n");
      out.write("<span style=\"margin-left:30px;\">현제 페이지 : <A href=\"/goodsServlet.mo?func=goods_001\">홈</A>>고객센터\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 게시판 제목 -->\r\n");
      out.write("<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t<tr><td colspan=\"2\" height=\"8\"></td></tr>\r\n");
      out.write("\t<tr> \r\n");
      out.write("\t\t<td width=\"10\"><img src=\"/images/common/bul_02_01.gif\"></td>\r\n");
      out.write("\t\t<td class=\"font16_title\"><font color=\"#666666\"><B>");
      out.print( bbsName);
      out.write("</B></font></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<hr color=\"#eeeeee\" noshade>\r\n");
      out.write("\r\n");
      out.write("<TABLE cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t<TR><TD height=\"15\"></TD></TR>\r\n");
      out.write("</TABLE>\r\n");
      out.write("<!-- 게시판 목록 출력 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<FORM name=\"bbsForm\" action=\"/supportServlet.mo\" method=\"post\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"func\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"seq\" value=\"");
      out.print( seq);
      out.write("\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"hit\" value=\"N\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"code\" value=\"");
      out.print( code);
      out.write("\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"pageNum\" value=\"");
      out.print( pageNum);
      out.write("\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"section\" value=\"");
      out.print( section);
      out.write("\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"word\" value=\"");
      out.print( word);
      out.write("\">\r\n");
      out.write("</FORM>\t\r\n");
      out.write("\r\n");
      out.write("<FORM name=\"fileDownloadForm\" action=\"/common/FileDownload.jsp\" method=\"post\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"savePath\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"saveName\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"orgName\">\r\n");
      out.write("</FORM>\r\n");
      out.write("\r\n");
      out.write("<CENTER>\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t<TR><TD height=\"15\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\r\n");
      out.write("\t<TABLE cellspacing=\"1\" cellpadding=\"5\" bgcolor=\"#7682EB\" width=\"250\">\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD align=\"center\" bgcolor=\"#74c900\" width=\"250\">\r\n");
      out.write("\t\t\t\t<FONT color=\"blue\" size=\"3\"><B>");
      out.print( bbsName);
      out.write("</B></FONT>\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t<TR><TD height=\"10\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\" width=\"700\">\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD width=\"700\">\r\n");
      out.write("\t\t\t\t<IMG src=\"/images/button/button_all_list.gif\" border=\"0\" onclick=\"listAction();\" style=\"cursor:hand\" align=\"absmiddle\">\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t<TR><TD height=\"2\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\r\n");
      out.write("\t<TABLE cellspacing=\"1\" cellpadding=\"5\" width=\"700\" bgcolor=\"#7682EB\">\r\n");
      out.write("\t\t<FORM name=\"updateForm\" action=\"/supportServlet.mo\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t<INPUT type=\"hidden\" name=\"func\" value=\"support_007\">\r\n");
      out.write("\t\t\t<INPUT type=\"hidden\" name=\"seq\" value=\"");
      out.print( seq);
      out.write("\">\r\n");
      out.write("\t\t\t<INPUT type=\"hidden\" name=\"code\" value=\"");
      out.print( code);
      out.write("\">\r\n");
      out.write("\t\t\t<INPUT type=\"hidden\" name=\"pageNum\" value=\"");
      out.print( pageNum);
      out.write("\">\r\n");
      out.write("\t\t\t<INPUT type=\"hidden\" name=\"section\" value=\"");
      out.print( section);
      out.write("\">\r\n");
      out.write("\t\t\t<INPUT type=\"hidden\" name=\"word\" value=\"");
      out.print( word);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD width=\"100\" align=\"center\" bgcolor=\"#74c900\"><B>작성자</B></TD>\r\n");
      out.write("\t\t\t\t<TD width=\"250\" bgcolor=\"#FFFFFF\"><B>");
      out.print( regName);
      out.write("</B>(");
      out.print( regId);
      out.write(")</TD>\r\n");
      out.write("\t\t\t\t<TD width=\"100\" align=\"center\" bgcolor=\"#74c900\"><B>조회수</B></TD>\r\n");
      out.write("\t\t\t\t<TD width=\"250\" bgcolor=\"#FFFFFF\">");
      out.print( hitCnt);
      out.write("</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD align=\"center\" bgcolor=\"#74c900\"><B>제 목</B></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\" colspan=\"3\"><INPUT type=\"text\" name=\"title\" value=\"");
      out.print( title);
      out.write("\" size=\"84\" maxlength=\"200\"></TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD align=\"center\" bgcolor=\"#74c900\" height=\"200\"><B>내 용</B></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\" colspan=\"3\" valign=\"top\"><TEXTAREA name=\"content\" cols=\"83\" rows=\"15\">");
      out.print( content);
      out.write("</TEXTAREA></TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\r\n");

	if(si.getFileYn())
	{

      out.write("\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD align=\"center\" bgcolor=\"#74c900\"><B>첨부파일</B></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\" colspan=\"3\" valign=\"top\">\r\n");

		if(supportFileList.size()>0)
		{

      out.write("\r\n");
      out.write("\t\t\t\t\t---------- 삭제할 첨부 파일에 체크하세요. ----------\r\n");
      out.write("\t\t\t\t\t<TABLE cellspacing=\"0\" cellpadding=\"0\" width=\"600\">\r\n");

			for(int i=0; i<supportFileList.size(); i++)
			{
				Hashtable fileTable = (Hashtable)supportFileList.get(i);
				String fileSeq = (String)fileTable.get("SEQ");	//글과 공유하는 시퀀스이기에 그냥 시퀀스를 넣으면 됨..
				String path = (String)fileTable.get("PATH");	//나머지는 뷰와 동일.
				String orgName = (String)fileTable.get("ORG_NAME");
				String saveName = (String)fileTable.get("SAVE_NAME");

				double fileSize = Double.parseDouble((String)fileTable.get("FILE_SIZE"));
				String sizeStr = fileSize + " Byte";
				if(fileSize>1024*1000)
				{
					fileSize =Math.round(fileSize/(1024*1000)*10)/10.0;
					sizeStr = fileSize + " MB";
				}
				else if(fileSize>1024)
				{
					fileSize = Math.round(fileSize/1024*10)/10.0;
					sizeStr = fileSize + " KB";
				}

				String imgName = "etc";
				if(orgName.lastIndexOf(".") != -1)
				{
					imgName = (orgName.substring(orgName.lastIndexOf(".")+1)).toLowerCase();
					if(!imgName.equals("bmp") && !imgName.equals("doc") && !imgName.equals("gif") && !imgName.equals("html") && !imgName.equals("hwp") && !imgName.equals("jpg") && !imgName.equals("pdf") && !imgName.equals("ppt") && !imgName.equals("txt") && !imgName.equals("xls") && !imgName.equals("zip"))
					{
						imgName = "etc";
					}
				}	//뷰 랑 비슷하긴한데. 인풋 의 이름이 deleteFile 이고 값이 시퀀스값이다. ... 수정화면에서도 다운로드가 됨ㅋ

      out.write("\r\n");
      out.write("\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TD valign=\"bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<INPUT type=\"checkbox\" name=\"deleteFile\" value=\"");
      out.print( fileSeq);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<A href=\"javascript:fileDownloadAction('");
      out.print( path);
      out.write("', '");
      out.print( saveName);
      out.write("', '");
      out.print( orgName);
      out.write("');\"><IMG src=\"/images/file/");
      out.print( imgName);
      out.write(".gif\" alt=\"");
      out.print( orgName);
      out.write("\" border=\"0\" align=\"absmiddle\">&nbsp;&nbsp;");
      out.print( orgName);
      out.write("</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t(<FONT color=\"#000099\">");
      out.print( sizeStr);
      out.write("</FONT>)\r\n");
      out.write("\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t</TR>\r\n");

			}

      out.write("\r\n");
      out.write("\t\t\t\t\t</TABLE>\r\n");
      out.write("\t\t\t\t\t<BR>\r\n");

		}

		if(supportFileList.size()<3)	//아직 지우지 않은 파일 이 있을때 나머지 업로드 가능 파일 수를 여기서 정해줌.
		{

      out.write("\r\n");
      out.write("\t\t\t\t\t---------- 새롭게 첨부할 파일을 선택하세요. ----------\r\n");
      out.write("\t\t\t\t\t<TABLE cellspacing=\"0\" cellpadding=\"0\" width=\"100%\">\r\n");

			for(int i=0; i<3-supportFileList.size(); i++)
			{

      out.write("\r\n");
      out.write("\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TD valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;<INPUT type=\"file\" name=\"upFile[");
      out.print( i);
      out.write("]\" size=\"40\"><BR>\r\n");
      out.write("\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t</TR>\r\n");

			}

      out.write("\r\n");
      out.write("\t\t\t\t\t</TABLE>\r\n");

		}

      out.write("\r\n");
      out.write("\t\t\t\t</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");

	}

      out.write("\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD align=\"center\" bgcolor=\"#74c900\"><B>등록일</B></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\">");
      out.print( regDate);
      out.write("</TD>\r\n");
      out.write("\t\t\t\t<TD align=\"center\" bgcolor=\"#74c900\"><B>최종수정일</B></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\">");
      out.print( updDate);
      out.write("</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t</FORM>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t<TR><TD height=\"5\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\" width=\"700\">\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD width=\"700\" align=\"center\">\r\n");

	if(writerYn || adminYn)
	{

      out.write("\r\n");
      out.write("\t\t\t\t<IMG src=\"/images/button/but_ok.gif\" border=\"0\" onclick=\"updateAction();\" style=\"cursor:hand\" align=\"absmiddle\">\r\n");

	}

      out.write("\r\n");
      out.write("\t\t\t\t<IMG src=\"/images/button/but_cancel1.gif\" border=\"0\" onclick=\"cancelAction();\" style=\"cursor:hand\" align=\"absmiddle\">\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t<TR><TD height=\"10\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\r\n");

	if(si.getAddYn())
	{
		for(int i=0; i<supportAddList.size(); i++)
		{
			Hashtable supportAddTable = (Hashtable)supportAddList.get(i);
			String addSeq = (String)supportAddTable.get("SEQ");
			String addName = (String)supportAddTable.get("NAME");
			String addRegId = (String)supportAddTable.get("REG_ID");
			String addRegDate = (String)supportAddTable.get("REG_DATE");
			String addContent = (String)supportAddTable.get("CONTENT");
			addContent = addContent.replaceAll("\n", "<BR>");

      out.write("\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t<TR><TD height=\"5\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"1\" cellpadding=\"3\" width=\"700\" bgcolor=\"#893C07\">\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD width=\"700\" bgcolor=\"#FCD7BE\">\r\n");
      out.write("\t\t\t\t<FONT size=\"2\" color=\"#9A9A9A\">");
      out.print( addName);
      out.write('(');
      out.print( addRegId);
      out.write(") : ");
      out.print( addRegDate);
      out.write("</FONT><BR>\r\n");
      out.write("\t\t\t\t");
      out.print( addContent);
      out.write("\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t</TABLE>\r\n");

		}
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t<TR><TD height=\"25\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("</CENTER>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
