/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-05-15 12:31:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bbs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import bbs.*;
import java.util.*;

public final class BbsUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      java.util.Hashtable outputTable = null;
      outputTable = (java.util.Hashtable) _jspx_page_context.getAttribute("outputTable", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (outputTable == null){
        outputTable = new java.util.Hashtable();
        _jspx_page_context.setAttribute("outputTable", outputTable, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      java.util.Hashtable inputTable = null;
      inputTable = (java.util.Hashtable) _jspx_page_context.getAttribute("inputTable", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (inputTable == null){
        inputTable = new java.util.Hashtable();
        _jspx_page_context.setAttribute("inputTable", inputTable, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");

	ArrayList bbsList = (ArrayList)outputTable.get("bbsList");

	Hashtable bbsTable = (Hashtable)bbsList.get(0);
	String seq = (String)bbsTable.get("SEQ");
	String title = (String)bbsTable.get("TITLE");
	String hitCnt = (String)bbsTable.get("HIT_CNT");
	String regDate = (String)bbsTable.get("REG_DATE");
	String updDate = (String)bbsTable.get("UPD_DATE");
	String regId = (String)bbsTable.get("REG_ID");
	String name = (String)bbsTable.get("NAME");
	String content = (String)bbsTable.get("CONTENT");

	boolean loginYn = false;
	boolean writerYn = false;
	boolean adminYn = false;
	if(session != null && session.getAttribute("loginYn")!=null && ((String)session.getAttribute("loginYn")).equals("Y"))
	{
		loginYn = true;
	}
	if(loginYn && regId.equals((String)session.getAttribute("id")))
	{
		writerYn = true;
	}
	if(loginYn && ((String)session.getAttribute("adminYn")).equals("Y"))
	{
		adminYn = true;
	}

	String code = (String)inputTable.get("code");
	BbsInfomation bi = new BbsInfomation(code);
	String bbsName = bi.getName();

	String pageNum = (String)inputTable.get("pageNum");
	String section = (String)inputTable.get("section");
	String word = (String)inputTable.get("word");

	ArrayList bbsFileList = new ArrayList();
	if(bi.getFileYn())
	{
		bbsFileList = (ArrayList)bbsTable.get("FILE_LIST");
	}

	ArrayList bbsAddList = new ArrayList();
	if(bi.getAddYn())
	{
		bbsAddList = (ArrayList)outputTable.get("bbsAddList");
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<SCRIPT language=\"JavaScript\">\r\n");
      out.write("\tfunction updateAction()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar f = document.updateForm;\r\n");
      out.write("\t\tif(trim(f.title.value)==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"제목을 입력하세요\");\r\n");
      out.write("\t\t\tf.title.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(trim(f.content.value)==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"본문을 입력하세요\");\r\n");
      out.write("\t\t\tf.content.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tf.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction listAction()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.bbsForm.func.value=\"bbs_001\";\r\n");
      out.write("\t\tdocument.bbsForm.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction cancelAction()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.bbsForm.func.value=\"bbs_004\";\r\n");
      out.write("\t\tdocument.bbsForm.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction fileDownloadAction(svPath, svName, ogName)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar f = document.fileDownloadForm;\r\n");
      out.write("\t\tf.savePath.value = svPath;\r\n");
      out.write("\t\tf.saveName.value = svName;\r\n");
      out.write("\t\tf.orgName.value = ogName;\r\n");
      out.write("\t\tf.submit();\r\n");
      out.write("\t}\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<FORM name=\"bbsForm\" action=\"/bbsServlet.mo\" method=\"post\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"func\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"seq\" value=\"");
      out.print( seq);
      out.write("\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"hit\" value=\"N\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"code\" value=\"");
      out.print( code);
      out.write("\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"pageNum\" value=\"");
      out.print( pageNum);
      out.write("\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"section\" value=\"");
      out.print( section);
      out.write("\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"word\" value=\"");
      out.print( word);
      out.write("\">\r\n");
      out.write("</FORM>\r\n");
      out.write("\r\n");
      out.write("<FORM name=\"fileDownloadForm\" action=\"/common/FileDownload.jsp\" method=\"post\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"savePath\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"saveName\">\r\n");
      out.write("\t<INPUT type=\"hidden\" name=\"orgName\">\r\n");
      out.write("</FORM>\r\n");
      out.write("\r\n");
      out.write("<CENTER>\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t<TR><TD height=\"15\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\r\n");
      out.write("\t<TABLE cellspacing=\"1\" cellpadding=\"5\" bgcolor=\"#7682EB\" width=\"250\">\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD align=\"center\" bgcolor=\"#CFDDFA\" width=\"250\">\r\n");
      out.write("\t\t\t\t<FONT color=\"blue\" size=\"3\"><B>");
      out.print( bbsName);
      out.write("</B></FONT>\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t<TR><TD height=\"10\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\" width=\"700\">\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD width=\"700\">\r\n");
      out.write("\t\t\t\t<IMG src=\"/images/button/button_all_list.gif\" border=\"0\" onclick=\"listAction();\" style=\"cursor:hand\" align=\"absmiddle\">\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t<TR><TD height=\"2\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\r\n");
      out.write("\t<TABLE cellspacing=\"1\" cellpadding=\"5\" width=\"700\" bgcolor=\"#7682EB\">\r\n");
      out.write("\t\t<FORM name=\"updateForm\" action=\"/bbsServlet.mo\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t<INPUT type=\"hidden\" name=\"func\" value=\"bbs_006\">\r\n");
      out.write("\t\t\t<INPUT type=\"hidden\" name=\"seq\" value=\"");
      out.print( seq);
      out.write("\">\r\n");
      out.write("\t\t\t<INPUT type=\"hidden\" name=\"code\" value=\"");
      out.print( code);
      out.write("\">\r\n");
      out.write("\t\t\t<INPUT type=\"hidden\" name=\"pageNum\" value=\"");
      out.print( pageNum);
      out.write("\">\r\n");
      out.write("\t\t\t<INPUT type=\"hidden\" name=\"section\" value=\"");
      out.print( section);
      out.write("\">\r\n");
      out.write("\t\t\t<INPUT type=\"hidden\" name=\"word\" value=\"");
      out.print( word);
      out.write("\">\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD width=\"100\" align=\"center\" bgcolor=\"#CFDDFA\"><B>작성자</B></TD>\r\n");
      out.write("\t\t\t\t<TD width=\"250\" bgcolor=\"#FFFFFF\"><B>");
      out.print( name);
      out.write("</B>(");
      out.print( regId);
      out.write(")</TD>\r\n");
      out.write("\t\t\t\t<TD width=\"100\" align=\"center\" bgcolor=\"#CFDDFA\"><B>조회수</B></TD>\r\n");
      out.write("\t\t\t\t<TD width=\"250\" bgcolor=\"#FFFFFF\">");
      out.print( hitCnt);
      out.write("</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD align=\"center\" bgcolor=\"#CFDDFA\"><B>제 목</B></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\" colspan=\"3\"><INPUT type=\"text\" name=\"title\" value=\"");
      out.print( title);
      out.write("\" size=\"84\" maxlength=\"200\"></TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD align=\"center\" bgcolor=\"#CFDDFA\" height=\"200\"><B>내 용</B></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\" colspan=\"3\" valign=\"top\"><TEXTAREA name=\"content\" cols=\"83\" rows=\"15\">");
      out.print( content);
      out.write("</TEXTAREA></TD>\r\n");
      out.write("\t\t\t</TR>\r\n");

	if(bi.getFileYn())
	{

      out.write("\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD align=\"center\" bgcolor=\"#CFDDFA\"><B>첨부파일</B></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\" colspan=\"3\" valign=\"top\">\r\n");

		if(bbsFileList.size()>0)
		{

      out.write("\r\n");
      out.write("\t\t\t\t\t---------- 삭제할 첨부 파일에 체크하세요. ----------\r\n");
      out.write("\t\t\t\t\t<TABLE cellspacing=\"0\" cellpadding=\"0\" width=\"600\">\r\n");

			for(int i=0; i<bbsFileList.size(); i++)
			{
				Hashtable fileTable = (Hashtable)bbsFileList.get(i);
				String fileSeq = (String)fileTable.get("SEQ");
				String path = (String)fileTable.get("PATH");
				String orgName = (String)fileTable.get("ORG_NAME");
				String saveName = (String)fileTable.get("SAVE_NAME");

				double fileSize = Double.parseDouble((String)fileTable.get("FILE_SIZE"));
				String sizeStr = fileSize + " Byte";
				if(fileSize>1024*1000)
				{
					fileSize =Math.round(fileSize/(1024*1000)*10)/10.0;
					sizeStr = fileSize + " MB";
				}
				else if(fileSize>1024)
				{
					fileSize = Math.round(fileSize/1024*10)/10.0;
					sizeStr = fileSize + " KB";
				}

				String imgName = "etc";
				if(orgName.lastIndexOf(".") != -1)
				{
					imgName = (orgName.substring(orgName.lastIndexOf(".")+1)).toLowerCase();
					if(!imgName.equals("bmp") && !imgName.equals("doc") && !imgName.equals("gif") && !imgName.equals("html") && !imgName.equals("hwp") && !imgName.equals("jpg") && !imgName.equals("pdf") && !imgName.equals("ppt") && !imgName.equals("txt") && !imgName.equals("xls") && !imgName.equals("zip"))
					{
						imgName = "etc";
					}
				}

      out.write("\r\n");
      out.write("\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TD valign=\"bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<INPUT type=\"checkbox\" name=\"deleteFile\" value=\"");
      out.print( fileSeq);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<A href=\"javascript:fileDownloadAction('");
      out.print( path);
      out.write("', '");
      out.print( saveName);
      out.write("', '");
      out.print( orgName);
      out.write("');\"><IMG src=\"/images/file/");
      out.print( imgName);
      out.write(".gif\" alt=\"");
      out.print( orgName);
      out.write("\" border=\"0\" align=\"absmiddle\">&nbsp;&nbsp;");
      out.print( orgName);
      out.write("</A>\r\n");
      out.write("\t\t\t\t\t\t\t\t(<FONT color=\"#000099\">");
      out.print( sizeStr);
      out.write("</FONT>)\r\n");
      out.write("\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t</TR>\r\n");

			}

      out.write("\r\n");
      out.write("\t\t\t\t\t</TABLE>\r\n");
      out.write("\t\t\t\t\t<BR>\r\n");

		}

		if(bbsFileList.size()<5)
		{

      out.write("\r\n");
      out.write("\t\t\t\t\t---------- 새롭게 첨부할 파일을 선택하세요. ----------\r\n");
      out.write("\t\t\t\t\t<TABLE cellspacing=\"0\" cellpadding=\"0\" width=\"100%\">\r\n");

			for(int i=0; i<5-bbsFileList.size(); i++)
			{

      out.write("\r\n");
      out.write("\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t<TD valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;<INPUT type=\"file\" name=\"upFile[");
      out.print( i);
      out.write("]\" size=\"40\"><BR>\r\n");
      out.write("\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t</TR>\r\n");

			}

      out.write("\r\n");
      out.write("\t\t\t\t\t</TABLE>\r\n");

		}

      out.write("\r\n");
      out.write("\t\t\t\t</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");

	}

      out.write("\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD align=\"center\" bgcolor=\"#CFDDFA\"><B>등록일</B></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\">");
      out.print( regDate);
      out.write("</TD>\r\n");
      out.write("\t\t\t\t<TD align=\"center\" bgcolor=\"#CFDDFA\"><B>최종수정일</B></TD>\r\n");
      out.write("\t\t\t\t<TD bgcolor=\"#FFFFFF\">");
      out.print( updDate);
      out.write("</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t</FORM>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t<TR><TD height=\"5\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\" width=\"700\">\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD width=\"700\" align=\"center\">\r\n");

	if(writerYn || adminYn)
	{

      out.write("\r\n");
      out.write("\t\t\t\t<IMG src=\"/images/button/but_ok.gif\" border=\"0\" onclick=\"updateAction();\" style=\"cursor:hand\" align=\"absmiddle\">\r\n");

	}

      out.write("\r\n");
      out.write("\t\t\t\t<IMG src=\"/images/button/but_cancel1.gif\" border=\"0\" onclick=\"cancelAction();\" style=\"cursor:hand\" align=\"absmiddle\">\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t<TR><TD height=\"10\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\r\n");

	if(bi.getAddYn())
	{
		for(int i=0; i<bbsAddList.size(); i++)
		{
			Hashtable bbsAddTable = (Hashtable)bbsAddList.get(i);
			String addSeq = (String)bbsAddTable.get("SEQ");
			String addName = (String)bbsAddTable.get("NAME");
			String addRegId = (String)bbsAddTable.get("REG_ID");
			String addRegDate = (String)bbsAddTable.get("REG_DATE");
			String addContent = (String)bbsAddTable.get("CONTENT");
			addContent = addContent.replaceAll("\n", "<BR>");

      out.write("\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t<TR><TD height=\"5\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t<TABLE cellspacing=\"1\" cellpadding=\"3\" width=\"700\" bgcolor=\"#893C07\">\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD width=\"700\" bgcolor=\"#FCD7BE\">\r\n");
      out.write("\t\t\t\t<FONT size=\"2\" color=\"#9A9A9A\">");
      out.print( addName);
      out.write('(');
      out.print( addRegId);
      out.write(") : ");
      out.print( addRegDate);
      out.write("</FONT><BR>\r\n");
      out.write("\t\t\t\t");
      out.print( addContent);
      out.write("\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t</TABLE>\r\n");

		}
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<TABLE cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t<TR><TD height=\"25\"></TD></TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("</CENTER>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
