/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-05-21 01:26:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.stock;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Stock_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<SCRIPT type=\"text/javascript\">\r\n");
      out.write("\tfunction stockDisplay()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: '/stock/StockPrice.xml',\r\n");
      out.write("\t\t\tdataType: 'xml',\r\n");
      out.write("\t\t\tsuccess: function(xml){\r\n");
      out.write("\t\t\t\tvar stockList = $(xml);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tstockList.find('STOCK').each(function(num){\r\n");
      out.write("\t\t\t\t\tvar stock = $(this);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar seq = stock.attr('seq');\r\n");
      out.write("\t\t\t\t\tvar pm = stock.attr(\"pm\");\r\n");
      out.write("\t\t\t\t\tvar name = stock.find('NAME').text();\r\n");
      out.write("\t\t\t\t\tvar price = stock.find('PRICE').text();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar updateText = name + \":\" + insertComma(price);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t$('#stock'+num).text(updateText);\r\n");
      out.write("\t\t\t\t\t$('#stockImg'+num).attr('src', '/images/stock/'+pm+'.jpg');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tself.setTimeout(\"stockDisplay()\", 5000);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction insertComma(text)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar newText = \"\"+text;\r\n");
      out.write("\r\n");
      out.write("\t\tvar nowLocation = newText.length;\r\n");
      out.write("\t\twhile((nowLocation -3)>0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tnowLocation = nowLocation -3;\r\n");
      out.write("\t\t\tvar aStr = newText.substring(0, nowLocation);\r\n");
      out.write("\t\t\tvar bStr = newText.substring(nowLocation);\r\n");
      out.write("\t\t\tnewText = aStr + \",\" + bStr;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\treturn newText;\r\n");
      out.write("\t}\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<TABLE width=\"1000\" cellspacing=\"1\" cellpadding=\"5\" bgcolor=\"#7682EB\" width=\"250\">\r\n");

	int count = 0;
	for(int i=0; i<4; i++)
	{

      out.write("\r\n");
      out.write("\t<TR bgcolor=\"#FFFFFF\">\r\n");

		for(int j=0; j<6; j++)
		{

      out.write("\r\n");
      out.write("\t\t<TD width=\"166\">\r\n");
      out.write("\t\t\t<B><SPAN id=\"stock");
      out.print( count);
      out.write("\"></SPAN></B><IMG id = \"stockImg");
      out.print( count);
      out.write("\" src=\"/images/stock/0.jpg\" width=\"13\" height=\"13\" align=\"absmiddle\">\r\n");
      out.write("\t\t</TD>\r\n");

			count++;
		}

      out.write("\r\n");
      out.write("\t</TR>\r\n");

	}

      out.write("\r\n");
      out.write("</TABLE>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT type=\"text/javascript\">stockDisplay();</SCRIPT>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
