/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-06-03 07:03:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	HttpSession session = request.getSession(false);
	if(session != null && session.getAttribute("loginYn")!=null && ((String)session.getAttribute("loginYn")).equals("Y"))
	{

      out.write("\r\n");
      out.write("<SCRIPT language=\"JavaScript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\talert(\"이미 로그인되어있습니다\");\r\n");
      out.write("\t\tdocument.location.href=\"/commonServlet.mo\";\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("\r\n");

	}
	else
	{

      out.write("\r\n");
      out.write("<SCRIPT>\r\n");
      out.write("\tfunction loginAction()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar loginF = document.loginForm;\r\n");
      out.write("\t\tif(loginF.id.value == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"ID를 반드시 입력해야 합니다.\");\r\n");
      out.write("\t\t\tloginF.id.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(loginF.id.value.length < 4 || loginF.id.value.length > 20)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"ID는 4자 이상 20자 이하 입니다.\");\r\n");
      out.write("\t\t\tloginF.id.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif(loginF.pw.value == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"비밀번호를 반드시 입력해야 합니다.\");\r\n");
      out.write("\t\t\tloginF.pw.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(loginF.pw.value.length < 4 || loginF.pw.value.length > 20)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"비밀번호를 4자 이상 20자 이하 입니다.\");\r\n");
      out.write("\t\t\tloginF.pw.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tloginF.func.value=\"member_005\";\r\n");
      out.write("\r\n");
      out.write("\t\tloginF.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction search_IdAction()\r\n");
      out.write("\t{\r\n");
      out.write("\t\twindow.location.href = \"/memberServlet.mo?func=member_011_1\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction search_PwAction()\r\n");
      out.write("\t{\r\n");
      out.write("\t\twindow.location.href = \"/memberServlet.mo?func=member_011_2\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction ruleAction()\r\n");
      out.write("\t{\r\n");
      out.write("\t\twindow.location.href = \"/memberServlet.mo?func=member_001\";\r\n");
      out.write("\t}\r\n");
      out.write("\t$(document).ready(function(){document.getElementById(\"id_input\").focus();});\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<!-- 로그인 화면 상단 바 -->\r\n");
      out.write("\t\t\t<img src=\"/images/member/t_login.png\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr><td height=\"50\"></td></tr>\r\n");
      out.write("\t<tr bgcolor=\"#FFFFFF\">\r\n");
      out.write("\t\t<td background=\"http://img0001.echosting.cafe24.com/front/type_b/image/title/top_t_bg02.gif\"><img src=\"http://img0001.echosting.cafe24.com/front/type_b/image/title/tle_login.gif\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<!-- UNIT u1t 시작 -->\t\r\n");
      out.write("\t<tr bgcolor=\"#FFFFFF\"> \r\n");
      out.write("\t\t<td height=\"20\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr bgcolor=\"#FFFFFF\"> \r\n");
      out.write("\t\t<td height=\"10\"> \r\n");
      out.write("\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t<td width=\"10\"><img src=\"http://img0001.echosting.cafe24.com/front/type_b/image/common/bul_04_01.gif\"></td>\r\n");
      out.write("\t\t\t\t\t<td class=\"font14_title\">회원로그인</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr bgcolor=\"#FFFFFF\"> \r\n");
      out.write("\t\t<td> \r\n");
      out.write("\t\t<table border=\"0\" cellpadding=\"7\" cellspacing=\"3\" width=\"100%\" bgcolor=\"#e9e9e9\">\r\n");
      out.write("\t\t\t<tr> \r\n");
      out.write("\t\t\t<td bgcolor=\"#ffffff\"> \r\n");
      out.write("\t\t\t<table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" height=\"150\">\r\n");
      out.write("\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t<td align=\"center\" width=\"350\"><img src=\"/images/member/login_img.jpg\" width=\"350\" height=\"310\" border=\"0\"></td>\r\n");
      out.write("\t\t\t\t<td width=\"20\" align=\"left\"><img src=\"/images/member/20.gif\" border=\"0\"></td>\r\n");
      out.write("\t\t\t\t<td align=\"center\" width=\"350\">\r\n");
      out.write("\t\t\t\t<table cellpadding=\"0\" cellspacing=\"0\" width=\"350\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"340\">\r\n");
      out.write("\t\t\t\t\t<table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><img src=\"/images/member/login_title.gif\" border=\"0\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"100\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"color:#555555;font-size:12;font-family:굴림;\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<FORM name=\"loginForm\" method=\"post\" action=\"/memberServlet.mo\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"func\" value=\"member_005\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"230\" align=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<font style=\"color:#555555;font-size:8pt;font-family:돋움;\">아이디</font> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"id\" id=\"id_input\" size=\"15\" class=\"input01\" tabindex=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td rowspan=\"2\" height=\"63\" align=\"center\"><input type=\"image\" src=\"/images/member/bt_login.gif\" border=\"0\" onclick=\"loginAction();\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"230\" align=\"right\"><font style=\"color:#555555;font-size:8pt;font-family:돋움;\">비밀번호</font> <input type=\"password\" name=\"pw\" size=\"15\" class=\"input01\" tabindex=\"2\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</FORM>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td height=\"80\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t<table border=\"0\" height=\"80\" bgcolor=\"#EFEFEF\" width=\"320\" cellpadding=\"0\" cellspacing=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td bgcolor=\"#ffffff\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table align=\"right\" border=\"0\" width=\"96%\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font style=\"color:#555555;font-size:8pt;font-family:돋움;\">아직 회원이 아니십니까?<br>환영합니다.</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"100\"><a href=\"/memberServlet.mo?func=member_001\"><img src=\"/images/member/bt_join.gif\" border=\"0\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td height=\"90\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t<table border=\"0\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"109\" height=\"30\"><img src=\"/images/member/login_line.gif\" border=\"0\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"140\"><font style=\"color:#555555;font-size:8pt;font-family:돋움;\">&nbsp;아이디를 잊으셨습니까?</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"JavaScript:search_IdAction();\"><img src=\"/images/member/bt_idfind.gif\" border=\"0\"></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"109\" height=\"30\"><img src=\"/images/member/login_line.gif\" border=\"0\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"140\"><font style=\"color:#555555;font-size:8pt;font-family:돋움;\">&nbsp;비밀번호를 잊으셨습니까?</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"JavaScript:search_PwAction();\"><img src=\"/images/member/bt_pwfind.gif\" border=\"0\"></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"10\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");

	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
