/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-05-28 15:20:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class SearchIdPw_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      java.util.Hashtable outputTable = null;
      outputTable = (java.util.Hashtable) _jspx_page_context.getAttribute("outputTable", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (outputTable == null){
        outputTable = new java.util.Hashtable();
        _jspx_page_context.setAttribute("outputTable", outputTable, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<SCRIPT language=\"JavaScript\">\r\n");
      out.write("\tfunction searchIdAction()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar f = document.idSearch;\r\n");
      out.write("\t\tif (f.name.value ==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"이름을 입력해주세요.\");\r\n");
      out.write("\t\t\tf.name.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (f.jumin1.value ==\"\" || f.jumin1.value.length < 6)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"주민등록번호 앞자리는 6자리가 되어야 합니다.\");\r\n");
      out.write("\t\t\tf.jumin1.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (f.jumin2.value ==\"\" || f.jumin2.value.length < 7)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"주민등록번호 뒷자리는 7자리가 되어야 합니다.\");\r\n");
      out.write("\t\t\tf.jumin2.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tf.name.value = trim(f.name.value);\r\n");
      out.write("\t\tf.jumin1.value = trim(f.jumin1.value);\r\n");
      out.write("\t\tf.jumin2.value = trim(f.jumin2.value);\r\n");
      out.write("\r\n");
      out.write("\t\twindow.open(\"/common/Progress.jsp\", \"idSearch\", \"toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, width=300, height=200\");\r\n");
      out.write("\r\n");
      out.write("\t\tf.func.value = \"member_012\";\r\n");
      out.write("\t\tf.target = \"idSearch\";\r\n");
      out.write("\t\tf.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction searchPwAction()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar f = document.pwSearch;\r\n");
      out.write("\t\tif (f.id.value ==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"아이디를 입력해주세요.\");\r\n");
      out.write("\t\t\tf.id.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (f.name.value ==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"이름을 입력해주세요.\");\r\n");
      out.write("\t\t\tf.name.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (f.passQ.value ==\"000\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"질문을 선택해주세요.\");\r\n");
      out.write("\t\t\tf.passQ.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (f.passA.value ==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.alert(\"질문에 대한 답을 입력해주세요.\");\r\n");
      out.write("\t\t\tf.passA.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tf.id.value = trim(f.id.value);\r\n");
      out.write("\t\tf.name.value = trim(f.name.value);\r\n");
      out.write("\r\n");
      out.write("\t\twindow.open(\"/common/Progress.jsp\", \"pwSearch\", \"toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, width=300, height=200\");\r\n");
      out.write("\r\n");
      out.write("\t\tf.func.value = \"member_013\";\r\n");
      out.write("\t\tf.target = \"pwSearch\";\r\n");
      out.write("\t\tf.submit();\r\n");
      out.write("\t}\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("\t<tr height=\"100\"><td></td><td></td></tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<form name=\"idSearch\" method=\"post\" action=\"/memberServlet.mo\">\r\n");
      out.write("\t\t\t\t<INPUT type=\"hidden\" name=\"func\" value=\"member_012\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>아이디 찾기</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>이&nbsp;&nbsp;&nbsp;름 : \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"name\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t주민등록번호 : <br><input type=\"text\" name=\"jumin1\" maxlength=\"6\"> - <input type=\"text\" name=\"jumin2\" maxlength=\"7\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"확인\" onclick=\"searchIdAction();\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td>\t\t\t\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<form name=\"pwSearch\" method=\"post\" action=\"/memberServlet.mo\">\r\n");
      out.write("\t\t\t\t<INPUT type=\"hidden\" name=\"func\" value=\"member_013\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>비밀번호 찾기</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>아이디 : <input type=\"text\" name=\"id\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>이&nbsp;&nbsp;&nbsp;름 : <input type=\"text\" name=\"name\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>비밀번호 질문 : \r\n");
      out.write("\t\t\t\t\t\t\t<SELECT name=\"passQ\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<OPTION value=\"000\">-----------------선  택------------------</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t");

								ArrayList passQList = (ArrayList)outputTable.get("passQList");
								for(int i = 0 ; i<passQList.size(); i++)
								{
									Hashtable passQTable = (Hashtable)passQList.get(i);
									String code = (String)passQTable.get("CODE");
									String passQ = (String)passQTable.get("PASS_Q");
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<OPTION value=\"");
      out.print(code);
      out.write('"');
      out.write('>');
      out.print(passQ);
      out.write("</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</SELECT>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>비밀번호 &nbsp;&nbsp;&nbsp;답 : <INPUT type=\"text\" name=\"passA\" maxlength=\"40\" size=\"44\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"button\" value=\"확인\" onclick=\"searchPwAction();\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"돌아가기\" onclick=\"document.location.href='memberServlet.mo'\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
